.gitignore, common/src/components/LoadingApp.tsx, common/src/components/index.js, common/src/components/index.ts, common/src/components/layout/index.ts, common/src/index.js, common/src/styles/index.ts, dashboard/webpack.config.js, host/src/AppBar.tsx, host/webpack.config.js
Fixes #1 
Maybe worth pulling it in now? Have just noticed that there is one or two useful lines in this.
=> #1 reduce bundle size

packages/template/.swcrc, packages/template/package.json, packages/template/public/index.html, packages/template/src/App.tsx, packages/template/src/Service.tsx, packages/template/src/bootstrap.tsx, packages/template/src/index.ts, packages/template/tsconfig.json, packages/template/webpack.config.js
=> Add template package

packages/common/src/styles/index.ts, packages/common/src/styles/theme.ts, packages/common/src/ui/components/NavLink.tsx, packages/host/src/AppDrawer.tsx
Fixes #34 
I combined the two approaches and `makeStyles` now infers the correct theme type 🤷
=> Add type augmentation for theme

packages/common/src/hooks/useDrawer.ts, packages/common/src/styles/index.ts, packages/common/src/styles/theme.ts, packages/common/src/ui/components/index.ts, packages/customers/src/CustomerContainer.tsx, packages/host/src/AppBar.tsx, packages/host/src/AppDrawer.tsx, packages/host/src/Host.tsx, packages/transactions/src/TransactionService.tsx
fixes #54 
Opens and closes the drawer based on screen size. Not much else in here really, just a small tidy and the example of adjusting components based on the media query.
=> responsive app drawer and styles on appbar

packages/common/src/ui/components/NavLink.tsx, packages/common/src/utils/testing.tsx, packages/customers/src/Nav.tsx
Fixes #59 
- The customer nav icon should be highlighted when you're viewing a customer invoice
=> Add app bar focusing/selecting update

.eslintrc.js, packages/common/src/utils/formatters.test.ts, packages/common/src/utils/formatters.ts, packages/config/index.ts, packages/config/package.json, packages/config/routes.ts, packages/config/tsconfig.json, packages/customers/src/CustomerContainer.tsx, packages/customers/src/Nav.tsx, packages/host/src/AppDrawer.tsx, packages/host/src/Host.tsx, packages/transactions/src/TransactionService.tsx
=> #43 routes to enums

.swcrc, jest.config.js, package.json, yarn.lock
Down to ~7s for me. Still seems long 🤔
=> Add swc remove ts-jest

.storybook/preview.js, packages/common/src/ui/components/buttons/Button.stories.tsx, packages/common/src/ui/components/buttons/IconButton.stories.tsx, packages/common/src/ui/components/buttons/TextButton.stories.tsx, packages/common/src/ui/components/buttons/UnstyledIconButton.stories.tsx
Fixes: a missed commit from the app bar button PR 🙄 
This was missed out somehow.
=> button stories

.storybook/preview.js, packages/config/src/index.ts, packages/host/package.json, yarn.lock
=> Add fontsource/inter and load it into storybook

packages/common/src/ui/components/inputs/Checkbox/Checkbox.tsx, packages/common/src/ui/icons/CheckboxChecked.tsx, packages/common/src/ui/icons/CheckboxDisabled.tsx, packages/common/src/ui/icons/CheckboxEmpty.tsx, packages/common/src/ui/icons/Icon.stories.tsx, packages/common/src/ui/icons/UnhappyMan.stories.tsx, packages/common/src/ui/icons/index.ts
Fixes #137 
and then gets a bit carried away with icons in storybook. What I was trying to do, was help people developing later, so that they can find the right icon easily.
=> #137 update checkbox icon

packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/ui/components/buttons/UnstyledIconButton.tsx, packages/host/src/AppBar.tsx
=> Add back button to navigate back the stack

.storybook/theme.js, packages/common/src/hooks/useHostContext.ts, packages/common/src/ui/components/index.ts, packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.stories.tsx, packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.test.tsx, packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx, packages/common/src/ui/components/navigation/Breadcrumbs/index.ts, packages/common/src/ui/components/navigation/NavLink/NavLink.stories.tsx, packages/common/src/ui/components/navigation/NavLink/NavLink.test.tsx, packages/common/src/ui/components/navigation/NavLink/NavLink.tsx, packages/common/src/ui/components/navigation/NavLink/index.ts, packages/common/src/ui/components/navigation/index.ts, packages/config/src/index.ts, packages/config/src/routes.ts, packages/customers/src/Nav.tsx, packages/host/src/AppBar.tsx, packages/host/src/AppDrawer.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx
Does some things for #117 
- Really I just added a ref and adjusted the styles for the `AppBar` to push down the content below when it expands
=> #117 expando app bar

packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/types/index.ts, packages/common/src/ui/components/buttons/UnstyledIconButton.tsx, packages/common/src/ui/components/index.ts, packages/common/src/ui/components/menus/ColorMenu/ColorMenu.tsx, packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx, packages/common/src/ui/layout/tables/columns/index.ts, packages/common/src/ui/layout/tables/hooks/useColumns.ts, packages/common/src/ui/layout/tables/index.ts, packages/mock-server/src/schema/Transaction.js, packages/mocks/src/handlers.ts, packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx, packages/transactions/src/api.ts
Fixes #149 
- I think this approach is OK. Using a special column rather than doing some tricky embedding of the color. I think the color is used sparingly enough that we don't need some sort of generic solution for it.
- I tried a few approaches to passing the `onChange` to the cell
- Tried to add in an `onChange` into the column definition. I wasn't able to correctly type this very well - I could add the function, but couldn't pass through more generics (for the `onChange` params). Would also likely need to add sorts of handlers into the column definition? (onSubmit, onClick) which would mean they all become optional and that's a bit lame.
- Another option is to add into the columns a `getHandler` function, which the cell can call, then the `ListView` can have a function which returns …
=> #149 update color

packages/common/src/hooks/index.ts, packages/common/src/intl/intlHelpers.test.tsx, packages/common/src/ui/components/buttons/Button.stories.tsx, packages/common/src/ui/components/buttons/Button.tsx, packages/common/src/ui/components/buttons/FlatButton.stories.tsx, packages/common/src/ui/components/buttons/FlatButton.tsx, packages/common/src/ui/components/buttons/IconButton.stories.tsx, packages/common/src/ui/components/buttons/IconButton.tsx, packages/common/src/ui/components/buttons/NavigationButton.tsx, packages/common/src/ui/components/buttons/TextButton.stories.tsx, packages/common/src/ui/components/buttons/TextButton.tsx, packages/common/src/ui/components/buttons/UnstyledIconButton.stories.tsx, packages/common/src/ui/components/buttons/UnstyledIconButton.tsx, packages/common/src/ui/components/errors/GenericErrorFallback.tsx, packages/common/src/ui/components/index.ts, packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.stories.tsx, packages/common/src/ui/layout/forms/Field.tsx, packages/common/src/ui/layout/forms/Label.tsx, packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx, packages/common/src/ui/layout/tables/components/index.ts, packages/host/src/DetailPanel.test.tsx, packages/host/src/DetailPanel.tsx
Had a play around and then it worked for me - want to give it a test and see if it works for you?
=> #import test

packages/common/src/styles/ThemeProvider.tsx, packages/common/src/ui/components/buttons/UnstyledIconButton.tsx, packages/common/src/ui/components/menus/DropdownMenu/DropdownMenu.stories.tsx
Fixes #197 
Missed this in the diff, damn codemod!
=> Add fix for spacing isuses

packages/host/src/AppDrawer.tsx
Fixes #201 
Removed styles that weren't adding anything and added a flex to the bottom bit. 
Tested big and small, collapsed and expanded.
=> tidy drawer styles

packages/common/src/ui/layout/tables/RemoteDataTable.tsx, packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx, packages/common/src/ui/layout/tables/components/Header/Header.tsx, packages/common/src/ui/layout/tables/context/TableContext.test.ts, packages/common/src/ui/layout/tables/context/TableContext.ts, packages/common/src/ui/layout/tables/context/index.ts, packages/common/src/ui/layout/tables/hooks/useColumns.ts, packages/common/src/ui/layout/tables/index.ts, packages/common/src/ui/layout/tables/types.ts, packages/common/src/utils/testing.tsx, packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx
Fixes #156 
This is what I ended up with. Not 100% happy and open to suggestions or scraping. Confused myself. Why do I do this!
=> Add selected row state

packages/common/package.json, packages/common/src/hooks/useDetailPanel.tsx, packages/common/src/hooks/usePagination/usePagination.ts, packages/common/src/hooks/useQueryParams/useQueryParams.ts, packages/common/src/index.ts, packages/common/src/ui/layout/tables/RemoteDataTable.tsx, packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx, packages/host/src/Host.tsx, packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx, yarn.lock
Bit of a prototype to see how you feel. Found plenty of problems and things to do better which is good.
The maintainer is trying to make this component basically as flexible as possible and putting it a good amount of work. The code base is nice and small enough to be very approachable.
Package issues:
- Bug when there is no results 🤔  https://kbar.vercel.app/ this is happening here, but just reports an error in the console. In dev, the oh noes! screen pops up.
- Types need some help but aren't too bad. For example the package that's being used for keyword matching can accept a string array for keywords, but the type is only a string.
- I have no idea how the shortcuts work 🤔 
- The actions are memoized, so if you're using an action where the perform is a closure, you'll get funny …
=> #spotlight

packages/dashboard/src/DashboardService.tsx, packages/dashboard/src/Widget.tsx
Fixes #202 
Had a small play with skeletons to make the dashboard a little more generic. 
Possibly not helpful 🤷‍♂️
=> dummy widgets

packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/ui/layout/tables/RemoteDataTable.tsx, packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx, packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx, packages/common/src/ui/layout/tables/components/Header/Header.stories.tsx, packages/common/src/ui/layout/tables/components/Header/Header.test.tsx, packages/common/src/ui/layout/tables/components/Header/Header.tsx, packages/host/src/Host.tsx, packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx
Fixes #208 
- This was a good lesson! In overthinking and overcomplicating things :)
=> #208 unresponsive pages

packages/common/package.json, packages/common/src/hooks/useQueryParams/useQueryParams.ts, packages/common/src/index.ts, packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx, packages/host/src/Host.tsx, packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx, yarn.lock
Removes kbar as it's causing too many issues right now and I forgot about it.
storybook and jest not working. And if I build my own version with `es5` then there's some other errors.
Will look into fixing it in a new branch
=> Remove kbar

packages/common/package.json, packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.test.ts, packages/common/src/hooks/useIsScreen/useIsLargeScreen.test.ts, packages/common/src/hooks/useIsScreen/useIsScreen.stories.tsx, packages/common/src/hooks/useListData/useListData.ts, packages/common/src/hooks/useRowRenderCount/useRowRenderCount.stories.tsx, packages/common/src/hooks/useSortBy/useSortBy.stories.tsx, packages/common/src/index.ts, packages/common/src/ui/components/buttons/Button.stories.tsx, packages/common/src/ui/components/buttons/FlatButton.stories.tsx, packages/common/src/ui/components/buttons/IconButton.stories.tsx, packages/common/src/ui/components/buttons/TextButton.stories.tsx, packages/common/src/ui/components/buttons/UnstyledIconButton.stories.tsx, packages/common/src/ui/components/inputs/Checkbox/Checkbox.stories.tsx, packages/common/src/ui/components/menus/ColorMenu/ColorMenu.stories.tsx, packages/common/src/ui/layout/tables/RemoteDataTable.tsx, packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx, packages/common/src/ui/layout/tables/components/DataRow/DataRow.test.tsx, packages/host/src/Host.tsx, packages/mock-server/src/schema/Transaction.js, yarn.lock
Fixes #209 
- New release of kbar adding es5 compiling added. I've not added all the code back as I 1) want to check it is working for you 2) maybe want to work out a better strategy to adding actions that is better than the mvp of throwing the actions around so much
- Import paths made the pages break - annoying
- Boxes around the buttons
- Not sure what the pagination issue was it seems to be OK
=> #209 demo server issues

packages/common/src/hooks/useHostContext.ts, packages/common/src/hooks/useRowRenderCount/useRowRenderCount.ts, packages/common/src/styles/theme.ts, packages/common/src/types/index.ts, packages/common/src/ui/icons/Home.tsx, packages/common/src/ui/icons/Icon.stories.tsx, packages/common/src/ui/icons/User.tsx, packages/common/src/ui/icons/index.ts, packages/dashboard/src/DashboardService.tsx, packages/host/src/Footer.stories.tsx, packages/host/src/Footer.test.tsx, packages/host/src/Footer.tsx, packages/host/src/Host.tsx
Fixes #150 
Add a footer which shows status of current user
=> Add status bar and footer

packages/mock-server/src/index.js, packages/mock-server/src/schema/Item.js, packages/mock-server/src/schema/Transaction.js, packages/mock-server/src/schema/data.js, packages/mocks/src/handlers.ts
I was trying to allow  the transactions to have the same items and also add an update to items
=> Add items to api

packages/common/src/hooks/useBoundingClientRect/useBoundingClientRect.ts, packages/common/src/hooks/useDebouncedValue/index.ts, packages/common/src/hooks/useDebouncedValue/useDebouncedValue.stories.tsx, packages/common/src/hooks/useDebouncedValue/useDebouncedValue.test.tsx, packages/common/src/hooks/useDebouncedValue/useDebouncedValue.ts
Fixes #221
There's still an issue with resizing the window trigger too many window dimension state changes which is annoying me. I thought to do that in a new issue, though.
=> #221 Opening drawer lag

packages/common/src/hooks/useBoundingClientRect/useBoundingClientRect.test.tsx, packages/common/src/hooks/useDebounce/useDebounceCallback.test.tsx, packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx, packages/common/src/hooks/useWindowDimensions/useWindowDimensions.test.ts
Crap, I forgot to push before merging
=> Add test fixes

packages/common/src/hooks/useListData/useListData.test.tsx, packages/common/src/hooks/useListData/useListData.ts, packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx, packages/common/src/ui/components/inputs/Autocomplete/utils.tsx, packages/common/src/ui/components/modals/ListSearch/ListSearch.tsx, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/worker/handlers.ts, packages/transactions/src/OutboundShipment/ListView/CustomerSearch.tsx, packages/transactions/src/OutboundShipment/ListView/ListView.tsx, packages/transactions/src/api.ts
Fixes #235 
- Adds a `CustomerSearch` component wrapper around `ListSearch` - unsure where to put it 🤔 
- Hooks up the customer search to be how we create an invoice now
=> #235 new outbound flow 3

packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
bother! missed a couple of commits.
=> #260 fefo logic

packages/common/src/types/index.ts, packages/common/src/ui/components/StatusCrumbs.stories.tsx, packages/common/src/ui/components/StatusCrumbs.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer.tsx, packages/invoices/src/OutboundShipment/DetailView/index.ts, packages/invoices/src/OutboundShipment/DetailView/types.ts, packages/invoices/src/OutboundShipment/utils.ts, packages/invoices/src/api.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/full-schema.ts
Starts #303 
- Wanted to stop here even though it's not complete, the 'hard' parts are done, the rest is mainly clean up and styling
TODOs
- Add a component using [mui stepper](https://mui.com/api/stepper/) for the content
- Extract this hover over popover thingy to a general case.
=> #303 invoice status popover

packages/common/src/styles/theme.ts, packages/common/src/ui/components/StatusCrumbs.tsx, packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.stories.tsx, packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.test.tsx, packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.tsx, packages/common/src/ui/components/steppers/VerticalStepper/index.ts
- Still need to clean up the popover and make it more generic
- struggled a bit with making the connector 'connect' up with the circle nicely.. this is what I've ended up with 🤷
=> 1 - #invoice status stepper

packages/common/src/hooks/useDetailPanel.tsx, packages/common/src/ui/icons/Icon.stories.tsx, packages/common/src/ui/icons/Sidebar.tsx, packages/common/src/ui/icons/index.ts
=> 4 - #316 more button

packages/host/webpack.config.js
Fixes #339 
Adding a `[contenthash]` to remove issues some reviewers are having on the demo site.
=> #339 cache busting

packages/common/src/hooks/useRowRenderCount/useRowRenderCount.test.tsx, packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/index.ts, packages/common/src/types/schema.ts, packages/common/src/ui/components/domain/StatusCrumbs/StatusCrumbs.tsx, packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx, packages/common/src/ui/layout/tables/components/Header/Header.test.tsx, packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx, packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/OutboundShipment/DetailView/index.ts, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.test.tsx, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx, packages/invoices/src/OutboundShipment/DetailView/types.ts, packages/invoices/src/OutboundShipment/ListView/ListView.tsx, packages/invoices/src/api.ts
Well this is turning out to be bigger than I anticipated :)
I have only converted over the detail query here and thought to make a new PR for others as it was a lot more changes than I expected.
=> Add use of typed invoice detail query

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/OutboundShipment/CustomerSearchInput.tsx, packages/invoices/src/OutboundShipment/ListView/CustomerSearch.tsx, packages/invoices/src/api.ts, packages/system/src/Customer/ListView/ListView.tsx
This does the names query.. 🤔  🤣
=> #356 organise types 3

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/worker/handlers.ts, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.stories.tsx, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx, packages/system/src/Item/Components/ItemSearchInput/index.ts, packages/system/src/Item/Components/index.ts, packages/system/src/Item/ListView/ListView.tsx, packages/system/src/Item/ListView/api.ts, packages/system/src/Item/hooks/index.ts, packages/system/src/Item/hooks/useItems/index.ts, packages/system/src/Item/hooks/useItems/useItems.ts, packages/system/src/Item/index.ts, packages/system/src/Item/types.ts, packages/system/src/Name/ListView/ListView.tsx
Fixes #328 
*Sigh* - Coin jar for each mess up with the generated file diff?
- I made `ItemSearchInput` in the `system/items` and all the queries are now in there
- I separated the `ItemListView` and general item queries, as we don't need to query for the stock lines for the list view
=> #328 shift item code

packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/index.ts, packages/common/src/types/schema.ts, packages/common/src/ui/components/buttons/ColorSelectButton.tsx, packages/common/src/ui/components/panels/DetailPanelSection.tsx, packages/dashboard/src/widgets/OutboundShipmentsWidget.tsx, packages/invoices/src/OutboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/OutboundShipment/DetailView/index.ts, packages/mock-server/src/data/data.ts
Fixes #382 
- Removed status/entered from additional info
- put comment into additional info
- made auto expand
=> #382 additional info section

packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx, packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx, packages/mock-server/src/api/resolvers.ts
Fixes #397 
- Adds a search label to the toolbar and updates the server to send the correct total count on filtered data sets.
=> #397 search label and pagination state

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx, packages/invoices/src/api.ts, packages/mock-server/src/schema/Invoice.ts, packages/mock-server/src/worker/handlers.ts
#273 
- Deletions - working with mock server and mock worker
=> #273 Mutants 6

packages/common/package.json, packages/common/src/operations.graphql, packages/common/src/types/index.ts, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx, packages/common/src/utils/dateFunctions.ts, packages/common/src/utils/index.ts, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, yarn.lock
Fixes #405 
- Pretty straight forward one, maybe?
=> #line insertion issues

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/system/src/Item/hooks/useItems/useItems.ts
=> #graphql schema update

packages/common/src/utils/arrays/utils.ts, packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.test.tsx, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx, packages/invoices/src/OutboundShipment/DetailView/types.ts, packages/invoices/src/OutboundShipment/utils.ts, packages/invoices/src/api.ts
Ugh.. I am unsure if this is all worthwhile at this point :)
- this updates the reducer and tests to work with the summary items rather than just rows
- Still need to fix up the actual item edit modal to work properly again!
=> #293 edit rows 3

packages/common/src/ui/components/index.ts, packages/common/src/ui/components/inputs/TextInput/ReadOnlyInput.tsx, packages/common/src/ui/forms/Modal/ModalNumericInput.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
#422 
- Has terrible UI, but think the functionality should be there
=> #422 fefo stock issuing

packages/common/src/hooks/useDialog/useDialog.stories.tsx, packages/common/src/hooks/useDialog/useDialog.test.tsx, packages/common/src/hooks/useDialog/useDialog.tsx, packages/common/src/intl/locales/ar.json, packages/common/src/intl/locales/en.json, packages/common/src/intl/locales/fr.json, packages/common/src/intl/locales/pt.json, packages/common/src/ui/components/inputs/TextInput/ReadOnlyInput.tsx, packages/common/src/ui/forms/Modal/ModalInput.tsx, packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx, packages/system/src/Item/hooks/useItemsList/useItemsList.ts
Fixes #427 
- Adds OK And next implementation
- Adds the changes from my last PR
=> #427 ok and next

packages/invoices/src/OutboundShipment/ListView/ListView.tsx, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/utils.ts
Fixes #430 
- Made it so stock lines are created with zero quantity and then the invoices are created, then we take all the inbound invoices, a random subset of stocklines and create some invoice lines - adding to the stock as we go. Then the same for the outbounds, taking a random subset of stock lines and some random percentage of the stock lines available quantity and adjusting stock as we go through.
- This actually ends up being simpler creation code, of course 🙄 
- feel free to change numbers if you want more/less data to be committed!
=> Add update to mock server to create inbound and outbound shipments

packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/types.ts, packages/invoices/src/utils.ts
#410 
- This is the API for the detail view
- also a few util changes
=> #410 - 1 Add inbound detail view api

packages/invoices/src/InboundShipment/DetailView/reducer/index.ts, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.test.ts, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts
#410 
- The reducer for the detail view
- You guessed it!
- I think if we stick with the summary items we will be able to use the same reducer for inbound and outbounds
=> Add inbound detail view reducer

packages/common/src/index.ts, packages/common/src/intl/locales/en/common.json, packages/common/src/ui/components/popover/HoverPopover/HoverPopover.tsx, packages/common/src/ui/layout/tables/columns/NotePopoverColumn/NotePopoverColumn.tsx, packages/common/src/ui/layout/tables/columns/RowExpand/RowExpand.tsx, packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx, packages/invoices/src/InboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/InboundShipment/DetailView/index.ts, packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/ListView/Toolbar.tsx, packages/invoices/src/InvoiceService.tsx, packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
Big one..  more copy and paste, though..
- Adds the detail view with the same components as the current outbound, less the item details modal
=> #410 inbound detail view 6

packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/index.ts, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts, packages/host/public/config.js, packages/host/src/bootstrap.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/ListView/ListView.tsx, packages/invoices/src/InboundShipment/ListView/api.ts, packages/invoices/src/OutboundShipment/DetailView/Footer.tsx, packages/invoices/src/OutboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/ListView/ListView.tsx, packages/invoices/src/OutboundShipment/ListView/api.ts, packages/invoices/src/types.ts, packages/invoices/src/utils.ts, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
#454 
Well I hope this isn't a bad idea. 
I think this will be all round better as we can implement the more complex things like handling errors
all up this took about 30 minutes. Should only take less to revert things as they come in to the server
=> Revert all incompatible changes

packages/common/src/intl/IntlProvider.tsx, packages/common/src/intl/locales/en/common.json, packages/host/src/bootstrap.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.ts, packages/invoices/src/InboundShipment/ListView/Toolbar.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer.tsx
Fixes #445 and #435
- Adds updating of an invoice features
- Few off roads that i'll point out!
=> #445 Updating an inbound

packages/common/src/hooks/useDialog/useDialog.tsx, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
Starting to work on #448 
- This is adding a modal to add an item.
- Offroad switch of the slide animation into `useDialog` which implicitly animates when you click the next button. Mainly this was just fun so I can remove if not useful..!
=> #448 invoice line edit 1

packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx
Just a very rough tab implementation to give an idea. I thought I wouldn't like tabs but turns out I quite like it. 
Would be good to determine if people actually use all the tabs or not. I imagine they don't?
Adding keyboard shortcuts to navigate between tabs would make it fine to use, I think. Could also add a 'summary' or 'totals' tab.
=> #448 Very rough tabbed implementation

packages/common/src/ui/layout/tables/components/Header/Header.tsx, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts, packages/invoices/src/OutboundShipment/DetailView/reducer.ts
Fixes #434 
Just fixing sorting which I broke when introducing the summary items
=> #434 detail view sorting broken

packages/common/src/ui/components/loading/Biker/Biker.tsx, packages/common/src/ui/components/loading/Biker/index.ts, packages/common/src/ui/components/loading/index.ts, packages/host/src/Host.tsx
Fixes #472 
It would be best if you load this and take a look before you look at the code..
It's the spinner when you first load the page!
=> #472 suspense loading spinner

packages/common/src/intl/locales/en/app.json, packages/common/src/intl/locales/en/common.json, packages/common/src/intl/locales/fr/app.json, packages/config/src/routes.ts, packages/host/src/Host.tsx, packages/host/src/components/AppDrawer/AppDrawer.tsx, packages/host/src/components/Navigation/InventoryNav.tsx, packages/host/src/components/Navigation/index.ts, packages/host/src/routers/InventoryRouter.tsx, packages/host/src/routers/index.ts, packages/system/src/Stock/Components/Toolbar.tsx, packages/system/src/Stock/Components/index.ts, packages/system/src/Stock/ListView/ListView.tsx, packages/system/src/Stock/ListView/api.ts, packages/system/src/Stock/ListView/index.ts, packages/system/src/Stock/Service/Service.tsx, packages/system/src/Stock/Service/index.ts, packages/system/src/Stock/index.ts, packages/system/src/Stock/types.ts, packages/system/src/index.ts
First step of the `Inventory` section. Moving the nav and router components out, as per `Distribution` etc.
=> add navigation for Inventory

packages/common/src/ui/layout/tables/DataTable.tsx, packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/TextInputCell/index.ts, packages/common/src/ui/layout/tables/components/Cells/index.ts, packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx, packages/common/src/ui/layout/tables/components/Header/Header.tsx, packages/common/src/ui/layout/tables/components/index.tsx, packages/common/src/ui/layout/tables/context/TableContext.ts, packages/common/src/ui/layout/tables/index.ts, packages/common/src/ui/layout/tables/types.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx, packages/invoices/src/types.ts
Thought I would float this idea - using `DataTable` as the table in the `InvoiceLineEdit` modal.
=> #448 inbound line editing 5

packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
=> Add more specific import paths

packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
Fixes #458 
- improves the behaviour I think
- I wanted to put this logic into a component .. "AutocompleteWithDefaultValue" ... and now i'm realising maybe there was a better way to do this with the default value prop.. crap
=> Add updated/improved item search input behaviour

packages/common/src/ui/layout/tables/DataTable.tsx, packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx, packages/common/src/ui/layout/tables/components/index.tsx, packages/common/src/ui/layout/tables/context/TableContext.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
Fixes #421 
Looks a bit better and a couple offroad fixes
=> #421 Add ui update for scrollbars

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/common/src/utils/formatters.ts, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.ts, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/schema/Invoice.ts, packages/mock-server/src/worker/handlers.ts
The never ending #448 !
This is enabling saving/persisting of inbound updates and inserts. Haven't got to deletes yet.
Is working for mocks and the dev branch (after recreating the database again... the current dev branch references `location`, so if thats not in your schema 💥
=> #448 inbound line edit 9

packages/common/src/intl/locales/en/common.json, packages/common/src/intl/locales/en/distribution.json, packages/common/src/styles/index.ts, packages/common/src/ui/components/loading/Biker/Biker.tsx, packages/common/src/ui/forms/Modal/ModalLabel.tsx, packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.ts, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.ts, packages/invoices/src/types.ts, packages/mock-server/src/data/database.ts
Fixes #448 ?!
- This adds deletion. Not deletion for individual batches right now, but for the whole line. Pretty much this catches inbound upto outbound current functionality and is enough to close #448, I reckon (so I can make new issues to replace it?)
- I added some style updates. I'm not impressed. Maybe you have a better idea for the background color. The problem I have is that the input backgrounds are what I want to use for a background 🤷
=> #448 inbound line edit 10

packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/reducer/reducer.ts, packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/invoices/src/OutboundShipment/DetailView/reducer.ts, packages/invoices/src/OutboundShipment/ListView/ListView.tsx, packages/invoices/src/types.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/types.ts
Just took the schema and added only the dashboard things. All the other additions are gone. Easier to update it 🤷
=> #512 Updated graphql schema

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/index.ts, packages/mock-server/src/schema/Requisition.ts, packages/mock-server/src/schema/index.ts
#513 part 1!
So far this is only the requisitions themselves and not any lines. A lot of boiler plate! Lines will simply be copy and pasting pretty much all of this code and replacing CustomerRequisition with CustomerRequisitionLine.
What are the chances we end up using Request and Response rather than supplier and customer? 100% I'd say.
=> #513 mock server requisition data 1

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/api/mutations.ts, packages/mock-server/src/api/resolvers.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/schema/Item.ts, packages/mock-server/src/schema/Requisition.ts
Fixes #513 
All the line stuff for reqs ... !
- Mutations for lines
- Adding lines to requisitions
All the values quantities are just floats because 1) I need to remember what they all do.. 2) would rather just do a new issue updating the values rather than jam it into this one 3) would have to have proper statuses and dates on all the transaction stuff to be able to count stock on hand and things properly - should be fine - will wait till some sort of ui gets started before doing more
=> #513 mock server requisition data 2

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/api/mutations/index.ts, packages/mock-server/src/api/mutations/stocktake.ts, packages/mock-server/src/api/resolvers/index.ts, packages/mock-server/src/api/resolvers/stocktake.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/index.ts, packages/mock-server/src/schema/Stocktake.ts, packages/mock-server/src/schema/index.ts
#514 - part 1 
This is the stocktakes themselves. Much easier now woo! Though, my copy paste fingers are getting sore..
=> #514 update mock server with stocktake data

packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/api/mutations/index.ts, packages/mock-server/src/api/mutations/stocktakeLine.ts, packages/mock-server/src/api/resolvers/index.ts, packages/mock-server/src/api/resolvers/stocktake.ts, packages/mock-server/src/api/resolvers/stocktakeLine.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/index.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/schema/Stocktake.ts
#514 
Adds very basic stock take lines and mutations
=> #514 mock server stocktake line data

packages/common/package.json, packages/config/package.json, packages/dashboard/package.json, packages/host/package.json, packages/host/src/routers/DistributionRouter.tsx, packages/host/src/routers/ReplenishmentRouter.tsx, packages/invoices/package.json, packages/mock-server/package.json, packages/requisitions/package.json, packages/requisitions/src/CustomerRequisition/DetailView/index.ts, packages/requisitions/src/CustomerRequisition/ListView/index.ts, packages/requisitions/src/CustomerRequisition/index.ts, packages/requisitions/src/RequisitionService.tsx, packages/requisitions/src/SupplierRequisition/DetailView/index.ts, packages/requisitions/src/SupplierRequisition/ListView/index.ts, packages/requisitions/src/SupplierRequisition/index.ts, packages/requisitions/src/index.ts, packages/requisitions/tsconfig.json, packages/system/package.json
Fixes #523 
- Just the boiler plate for the requisitions package
=> Add requisitions boilerplate

packages/common/src/intl/locales/en/common.json, packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts, packages/mock-server/src/api/resolvers/requisition.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/worker/handlers.ts, packages/requisitions/src/RequisitionService.tsx, packages/requisitions/src/SupplierRequisition/ListView/AppBarButtons.tsx, packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx, packages/requisitions/src/SupplierRequisition/ListView/Toolbar.tsx, packages/requisitions/src/SupplierRequisition/ListView/api.ts, packages/requisitions/src/SupplierRequisition/ListView/index.ts, packages/requisitions/src/types.ts
Fixes #525 
Just a basic supplier requisition view - a lot of copy paste suprisngly???
=> #525 supplier requisition list view

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/schema/Requisition.ts, packages/mock-server/src/worker/handlers.ts, packages/requisitions/src/CustomerRequisition/ListView/AppBarButtons.tsx, packages/requisitions/src/CustomerRequisition/ListView/ListView.tsx, packages/requisitions/src/CustomerRequisition/ListView/Toolbar.tsx, packages/requisitions/src/CustomerRequisition/ListView/api.ts, packages/requisitions/src/CustomerRequisition/ListView/index.ts
Fixes #526 
- And the winner of the most code copy and pasted goes to.....
=> Add customer requisition list view

packages/common/src/intl/locales/en/app.json, packages/config/src/routes.ts, packages/host/package.json, packages/host/src/components/Navigation/InventoryNav.tsx, packages/host/src/routers/InventoryRouter.tsx, packages/inventory/package.json, packages/inventory/src/InventoryService.tsx, packages/inventory/src/Stocktake/DetailView/index.ts, packages/inventory/src/Stocktake/ListView/index.ts, packages/inventory/src/Stocktake/index.ts, packages/inventory/src/index.ts, packages/inventory/tsconfig.json
Fixes #529 
- While doing this I noticed the `Stock` package and wondered if I put this in the wrong place. Hm.
=> Add inventory package

packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/mock-server/src/data/data.ts, packages/requisitions/src/SupplierRequisition/DetailView/SidePanel.tsx, packages/requisitions/src/SupplierRequisition/DetailView/Toolbar.tsx, packages/requisitions/src/SupplierRequisition/DetailView/api.ts, packages/requisitions/src/SupplierRequisition/DetailView/reducer.ts, packages/requisitions/src/types.ts, packages/requisitions/src/utils.ts
FIxes #536
- Adds the upsert for supplier requisition detail view
- Also adds updating of a few requisition fields
=> Add updated mutations for supplier requisitions

.github/workflows/bundle-size-diff.yaml, packages/host/package.json, packages/host/webpack.config.js
Fixes #13 
Not strictly necessary, but thought it might be a good learning experience. who knows.. might be useful 🤷 
Will need to get the webpack change into main before it works.. without it, the `stats.json` isn't generated of course and so we can't compare
=> #13 bundle size diff

packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx, packages/inventory/src/Stocktake/DetailView/DetailView.tsx, packages/inventory/src/Stocktake/DetailView/Footer.tsx, packages/inventory/src/Stocktake/DetailView/SidePanel.tsx, packages/inventory/src/Stocktake/DetailView/Toolbar.tsx, packages/inventory/src/Stocktake/DetailView/api.ts, packages/inventory/src/Stocktake/DetailView/index.ts, packages/inventory/src/Stocktake/DetailView/reducer.ts, packages/inventory/src/types.ts, packages/inventory/src/utils.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/worker/handlers/stocktake/index.ts
Fixes #546 
Just some more boilerplate for a basic stocktake detail view
=> #546 Basic stocktake detail view

packages/host/src/routers/DistributionRouter.tsx, packages/host/src/routers/ReplenishmentRouter.tsx, packages/mock-server/src/api/resolvers/name.ts, packages/mock-server/src/data/data.ts, packages/system/src/Name/ListView/ListView.tsx, packages/system/src/Name/ListView/api.ts, packages/system/src/Name/Service/Service.tsx, packages/system/src/Name/Service/index.ts
Fixes #546 
Well that was easy!
=> #549 Add supplier page

packages/common/src/types/index.ts, packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx, packages/common/src/ui/layout/tables/components/index.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx, packages/system/src/Item/hooks/useItem/useItem.ts, packages/system/src/Item/hooks/useItemsList/useItemsList.ts, packages/system/src/Item/utils.ts
Fixes #464 
I haven't taken into account the allocated but unsaved quantities when showing available quantity in the item list - currently the modal doesn't adjust the Available Quantity value when you allocate rows and that seems ok to me. Even so.. I've now changed the form, so that the available updates when you allocate. I like it - but what do you think?
=> #464 available quantity

packages/inventory/src/Stocktake/ListView/ListView.tsx
Fixes #562 
- Simply removing the customer search modal 
- Also reordered columns.. thought it looked better
=> #562 Remove selecting of a customer when creating a stocktake

packages/inventory/src/Stocktake/DetailView/SidePanel.tsx, packages/inventory/src/Stocktake/DetailView/Toolbar.tsx, packages/inventory/src/Stocktake/DetailView/api.ts, packages/inventory/src/Stocktake/DetailView/reducer.ts
Fixes #568 
- Just a simple description input 😁
=> #568 stocktake description field

packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/inventory/src/Stocktake/DetailView/Footer.tsx, packages/inventory/src/Stocktake/DetailView/api.ts, packages/inventory/src/Stocktake/DetailView/reducer.ts, packages/inventory/src/types.ts, packages/inventory/src/utils.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts
Fixes #588 
- Just adds the toggle button and disables the ok * next status button when on hold
- didnt prevent the deletion - putting on to https://github.com/openmsupply/openmsupply-client/issues/450
=> #588 locked stocktake

packages/common/src/intl/locales/en/common.json, packages/common/src/operations.graphql, packages/common/src/schema.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/worker/handlers/requisition/index.ts, packages/requisitions/src/CustomerRequisition/DetailView/api.ts, packages/requisitions/src/CustomerRequisition/ListView/ListView.tsx, packages/requisitions/src/CustomerRequisition/ListView/api.ts, packages/requisitions/src/SupplierRequisition/DetailView/api.ts, packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx, packages/requisitions/src/SupplierRequisition/ListView/api.ts, packages/requisitions/src/types.ts
Fixes #559 
- Added an order date column
- made the header reqnum -> Number
- added the color column and made the update work correctly
=> #559 requisition list view columns

packages/host/webpack.config.js
=> disable stats file in development

packages/common/src/types/schema.ts, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx, packages/mock-server/src/data/data.ts
=> #618 existing lines take 2

packages/common/src/additions.schema.graphql, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/InboundShipment/Dashboard/api.ts, packages/invoices/src/OutboundShipment/Dashboard/api.ts, packages/mock-server/src/api/resolvers/statistics.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/schema/Statistics.ts, packages/mock-server/src/worker/handlers/experimental.ts
Fixes #632 
- the `created` isn't supported yet so just randomising a number. Everything else seems straight forward
=> Add updated invoiceCounts

packages/common/src/ui/components/domain/StatusCrumbs/StatusCrumbs.tsx, packages/common/src/ui/components/popover/PaperPopover/PaperPopover.tsx
Fixes #628 
- Just added auto height/width when not specified
=> Add auto heigh/width for paper popover when not specified

packages/common/src/additions.schema.graphql, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/dashboard/src/api.ts, packages/invoices/src/InboundShipment/Dashboard/api.ts, packages/invoices/src/OutboundShipment/Dashboard/api.ts, packages/mock-server/src/worker/handlers/experimental.ts
=> remove counts from mocks

packages/common/src/utils/arrays/utils.ts, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
Fixes #650 
I now have a problem with focus - when you start typing into a field, pause, and the page rerenders the input, you lose focus and have to click in the text area/field again which is super annoying. have left that little issue for now.
=> ignore status in shipment updates

packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx
Fixes #647 
🤷 
Pretty confident this will make a comeback when the API has more available data, but for now..
=> Remove info column

packages/common/src/hooks/useDialog/useDialog.tsx, packages/common/src/types/schema.ts, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #655 
- Bit big sorry, though a lot of the diff is that damn schema.
- Went a bit far changing things up, but it seems to make things easier..
- Basically changed things up to use a lot more react-query based hooks rather than passing props around and putting a lot of the callbacks etc into the `InboundLineEdit` component rather than the parent `DetailView`
=> #655 dont update inbound when upserting items

packages/common/src/hooks/useDrawer.ts, packages/common/src/intl/locales/en/inventory.json, packages/common/src/intl/locales/en/replenishment.json, packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx, packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx, packages/host/src/components/AppDrawer/AppDrawer.tsx, packages/host/src/components/Navigation/useNestedNav.ts, packages/inventory/src/Stocktake/DetailView/SidePanel.tsx, packages/invoices/src/InboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/OutboundShipment/DetailView/SidePanel.tsx, packages/requisitions/src/CustomerRequisition/DetailView/SidePanel.tsx, packages/requisitions/src/SupplierRequisition/DetailView/SidePanel.tsx
Fixes #249 
Tidied the behaviour of the hover for the left nav, as that was annoying me. This might be more annoying 🤷  see what you think..
- hover over is the same
- hover out no longer collapses the menu; this avoids the jumping around
- when a menu item is clicked the state is reset and so any menu sections which were expanded due to the hover, are collapsed
- if the left nav is closed (ie the small screen view) then the hover still opens it, and when you aren't hovering over any menu items, it collapses again
=> #249 url is deadend

packages/common/src/ui/layout/tables/DataTable.tsx
Fixes #361 
turned out, wasn't too bad 😁 
had to add a background colour ( was transparent, and the body cells showed through! ) and a z-index ( the colour picker and checkbox cells were showing 🙄  )
=> stick header row

packages/common/src/hooks/useDialog/useDialog.tsx, packages/common/src/intl/locales/en/replenishment.json, packages/common/src/localStorage/LocalStorage.ts, packages/common/src/localStorage/keys.ts, packages/common/src/ui/layout/tables/columns/RowExpand/RowExpand.tsx, packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/invoices/src/InboundShipment/ListView/ListView.tsx, packages/invoices/src/InboundShipment/ListView/api.ts, packages/invoices/src/OutboundShipment/DetailView/Footer.tsx, packages/invoices/src/OutboundShipment/DetailView/reducer.ts, packages/invoices/src/OutboundShipment/ListView/api.ts, packages/invoices/src/types.ts, packages/invoices/tsconfig.json, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
Fixes #666 
Not as many as I thought!
=> #666 Add ts fixes

packages/inventory/src/types.ts, packages/mock-server/src/api/resolvers/name.ts, packages/mock-server/src/api/resolvers/stocktake.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/data/types.ts, packages/mock-server/src/schema/Invoice.ts, packages/mock-server/src/schema/Name.ts, packages/mock-server/src/schema/Requisition.ts, packages/mock-server/src/schema/Stocktake.ts, packages/mock-server/tsconfig.json
Fixes #670 
- Was mainly "Need all files under ./src"
- Would prefer to just import like `@openmsupply-client/common` but the tsconfig path and also the window object are givin me issues 🤔
=> Add fix mock server types

packages/common/src/additions.schema.graphql, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/components/buttons/ColorSelectButton.tsx, packages/requisitions/src/CustomerRequisition/DetailView/reducer.ts, packages/requisitions/src/SupplierRequisition/DetailView/DetailView.tsx, packages/requisitions/src/SupplierRequisition/DetailView/reducer.ts, packages/requisitions/src/types.ts, packages/requisitions/tsconfig.json
Fixes #672 
- Maybe the nullable dates shouldn't be a thing. Looking to change this up and remove the reducer anyway, though, so.. 🤷
=> Add updated requisition types

packages/common/src/intl/locales/en/inventory.json, packages/inventory/src/Stocktake/DetailView/DetailView.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLinePanel.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts, packages/inventory/src/utils.ts, packages/inventory/tsconfig.json
Fixes #671 
- Fixing a few types!
=> Add updated inventory types

packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx, packages/common/src/ui/layout/tables/components/Expand/index.ts, packages/common/src/ui/layout/tables/components/index.tsx, packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx, packages/invoices/src/InboundShipment/DetailView/columns.ts, packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
Fixes #675 
- Wasn't sure of the naming .. but added a 'minitable' in an 'expand' folder
- Didn't go 'full generic' .. thought this was enough
=> Add MiniTable expando component and use in outbound/inbound

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/DataTable.tsx, packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/ListView/ListView.tsx, packages/invoices/src/InboundShipment/ListView/api.ts, packages/invoices/src/OutboundShipment/DetailView/SidePanel.tsx, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/ListView/ListView.tsx, packages/invoices/src/OutboundShipment/ListView/api.ts, packages/invoices/src/types.ts, packages/mock-server/src/data/data.ts, packages/mock-server/src/data/database.ts, packages/mock-server/src/worker/handlers/invoice/index.ts, packages/requisitions/src/CustomerRequisition/DetailView/api.ts, packages/requisitions/src/CustomerRequisition/ListView/ListView.tsx, packages/requisitions/src/SupplierRequisition/DetailView/api.ts, packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx
Fixes #691 
- Adds color back to the listviews and detail views of invoices.
- Offroad fixed a dom validation problem that was coming up with the pagination row
=> #691 add a bit of color to invoices

packages/common/src/ui/components/popover/BasePopover/usePopover.tsx, packages/common/src/ui/layout/tables/columns/NotePopoverColumn/NotePopoverColumn.tsx, packages/host/src/bootstrap.tsx, packages/invoices/src/InboundShipment/DetailView/columns.ts, packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx, packages/mock-server/src/data/data.ts
Fixes #688 
- Adds handling of multiple notes
- Done it quite differently, but I think it works OK and allows for a reasonably diverse range of uses.
- Also the hovering was doing that weird dissapear and reappear thing so have tried to adjust the virtual ref slightly
=> #688 Handle multiple notes

packages/common/src/ui/layout/tables/DataTable.tsx
Fixes #693 
Finding the transition a little strange, but it's something! better than what it was 🤷‍♂️ 
See what you think anyway. I did try some of the other options - `Collapse` was the best option. Didn't try sliding in the whole table though, so that's still an option. I just liked the rows animating and using the TransitionGroup is easy
=> animate group transition

packages/common/src/intl/locales/en/app.json, packages/common/src/intl/locales/en/common.json, packages/common/src/ui/components/buttons/standard/ButtonWithIcon.stories.tsx, packages/common/src/ui/components/navigation/ExternalNavLink.tsx, packages/common/src/ui/components/navigation/index.ts, packages/host/src/components/AppBar/AppBar.tsx, packages/host/src/components/AppBar/SectionIcon.tsx, packages/host/src/components/AppDrawer/AppDrawer.tsx, packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx, packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx, packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx, packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx, packages/requisitions/src/CustomerRequisition/DetailView/AppBarButtons.tsx, packages/requisitions/src/CustomerRequisition/ListView/AppBarButtons.tsx, packages/requisitions/src/SupplierRequisition/DetailView/AppBarButtons.tsx, packages/requisitions/src/SupplierRequisition/ListView/AppBarButtons.tsx
Fixes #680 
moved docs to the bottom section of the app drawer, touching as many files as possible for such a simple change 🤷
=> move docs link

packages/common/package.json, packages/common/src/api/README.md, packages/common/src/api/hooks/README.md, packages/common/src/api/hooks/index.ts, packages/common/src/api/hooks/useFieldsSelector/README.md, packages/common/src/api/hooks/useFieldsSelector/index.ts, packages/common/src/api/hooks/useFieldsSelector/useFieldsSelector.ts, packages/common/src/api/hooks/useQuerySelector/README.md, packages/common/src/api/hooks/useQuerySelector/index.ts, packages/common/src/api/hooks/useQuerySelector/useQuerySelector.ts, packages/common/src/api/index.ts, yarn.lock
Doesn't do much for 717 - just adding some utility hooks!
=> #717 Add utility api hooks

packages/host/src/Host.tsx
Fixes #722 
Should add something better at some point. Maybe something with the mSupply man. Thought even using the mobile square spinner might be nice
=> Add replace biker man with boring loading spinner

packages/common/src/intl/locales/en/inventory.json, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/common/src/types/utility.ts, packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx, packages/inventory/src/Stocktake/DetailView/ContentArea.tsx, packages/inventory/src/Stocktake/DetailView/DetailView.tsx, packages/inventory/src/Stocktake/DetailView/Footer.tsx, packages/inventory/src/Stocktake/DetailView/SidePanel.tsx, packages/inventory/src/Stocktake/DetailView/Toolbar.tsx, packages/inventory/src/Stocktake/DetailView/columns.ts, packages/inventory/src/Stocktake/api/api.ts, packages/inventory/src/Stocktake/api/hooks.ts, packages/inventory/src/Stocktake/api/index.ts, packages/mock-server/src/worker/handlers/stocktake/index.ts
Fixes #716 
- Just does the stocktake itself for now. Will do the lines next.
=> #716 Remove save button from stocktake

packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx, packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.stories.tsx, packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx, packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx, packages/common/src/ui/components/inputs/Select/Select.stories.tsx, packages/common/src/ui/components/inputs/Select/Select.tsx, packages/common/src/ui/components/inputs/Switch/Switch.stories.tsx, packages/common/src/ui/components/inputs/Switch/Switch.tsx, packages/common/src/ui/components/inputs/TextArea/TextArea.stories.tsx, packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx, packages/common/src/ui/components/inputs/TextInput/TextInput.stories.tsx
Fixes #725 
Added a different background for the disabled input states and updated the stories to demonstrate / test these.
=> #725 disabled state

packages/common/src/intl/locales/en/inventory.json, packages/common/src/ui/layout/tables/DataTable.tsx, packages/inventory/src/Stocktake/DetailView/ContentArea.tsx, packages/inventory/src/Stocktake/DetailView/DetailView.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLinePanel.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks.ts, packages/inventory/src/Stocktake/api/hooks.ts, packages/inventory/src/utils.ts, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditPanel.tsx, packages/system/src/Item/index.ts, packages/system/src/Item/types.ts, packages/system/src/Item/utils.ts
Fixes #735 
- Makes next, OK and add batch buttons work
=> #735 stocktake add item buttons

packages/invoices/src/OutboundShipment/api/api.ts
- An effort to try and break down the issue.
- Somewhat of an arbitrary split in code to PR this. It's essentially just a copy paste of the current queries into this folder similar to how the other packages are structured
=> #715 Add API Folder

packages/invoices/src/OutboundShipment/DetailView/columns.ts, packages/invoices/src/OutboundShipment/api/hooks.ts, packages/invoices/src/types.ts
Fixes #715 
- Another annoying one - but this is heavily relying on types and copy paste to know it's at least.. close to correct? :)
- Buuut this is a huge diff out of the way which is really just setting up the columsn and the hooks which are similar pattern to what we've done already. In fact, the hooks are almost so generic this might even not be needed soon 🤔
=> #715 remove outbound shipment save button 2

packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
Fixes #752  (again)
Sorry! found another problem.. when changing the item, the pack sizes weren't updating.
Had just fixed and was about to push the change.. when you beat me to it and merged!
Creating the PR to track the change 😉
=> outbound edit modal

packages/common/src/ui/components/buttons/ButtonShowcase.stories.tsx, packages/common/src/ui/components/buttons/FlatButton.stories.tsx, packages/common/src/ui/components/buttons/FlatButton.tsx, packages/common/src/ui/components/panels/DetailPanelAction.tsx, packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx, packages/common/src/ui/icons/Filter.tsx, packages/common/src/ui/icons/Icon.stories.tsx, packages/common/src/ui/icons/index.ts
Fixes #596 
Just to get the issue out of the way really. all it does is add the filter icon and update a few props to allow the styling. Demo in storybook
=> FlatButton updates

packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditForm.tsx, packages/system/src/Item/hooks/useItemsList/useItemsList.ts
#785 
The filter was incorrect and was showing only items that were already in the invoice, rather than the reverse.
=> Add correct filtering condition

packages/common/src/intl/locales/en/distribution.json, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditForm.tsx, packages/invoices/src/OutboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/hooks.ts, packages/mock-server/src/worker/handlers/invoice/index.ts
#777 
- Adds delete functionality for lines.
- Not exactly what to do about errors - at the moment, ignoring them 🤔 
- Also might want a confirmation dialog, but i'm unsure
=> #777 os todo delete outbound lines

packages/common/src/intl/locales/en/distribution.json, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx, packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/OutboundShipment/DetailView/api.ts, packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditForm.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/useDraftOutboundLines.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/useNextItem.test.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/useNextItem.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/usePackSizeController.test.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/usePackSizeController.tsx, packages/invoices/src/OutboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/hooks.ts, packages/mock-server/src/worker/handlers/invoice/index.ts
Part of #777 
- Just splitting the PR up
- This is adding tests for the packSizeController and a quick fix also
=> #777 Add packSizeController tests

packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts, packages/system/src/Stock/ListView/ListView.tsx, packages/system/src/Stock/ListView/api.ts, packages/system/src/Stock/types.ts
Fixes #803 
Simple addition and wee tweak to the column widths
=> add column

packages/common/src/ui/components/buttons/ButtonShowcase.stories.tsx, packages/common/src/ui/components/buttons/SplitButton.stories.tsx, packages/common/src/ui/components/buttons/SplitButton.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer/index.ts, packages/invoices/src/utils.ts
Fixes #813 
- Not really sure if the UX for this is the best, but thought to leave it here and start getting feedback
=> #813 skipping outbound statuses

packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx, packages/invoices/src/InboundShipment/DetailView/Footer/index.ts, packages/invoices/src/utils.ts
Fixes #792 
- This implements the confirmation for inbound shipments confirmation modal
=> Add status change confirmation

packages/requisitions/src/SupplierRequisition/DetailView/ContentArea.tsx, packages/requisitions/src/SupplierRequisition/DetailView/DetailView.tsx, packages/requisitions/src/SupplierRequisition/DetailView/Footer.tsx, packages/requisitions/src/SupplierRequisition/DetailView/SidePanel.tsx, packages/requisitions/src/SupplierRequisition/DetailView/Toolbar.tsx, packages/requisitions/src/SupplierRequisition/DetailView/columns.ts, packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx, packages/requisitions/src/SupplierRequisition/ListView/api.ts, packages/requisitions/src/SupplierRequisition/api/api.ts, packages/requisitions/src/SupplierRequisition/api/hooks.ts, packages/requisitions/src/SupplierRequisition/api/index.ts, packages/requisitions/src/SupplierRequisition/api/operations.generated.ts, packages/requisitions/src/SupplierRequisition/api/operations.graphql, packages/requisitions/src/utils.ts
#831 - 1!
- This mainly adds the new queries and gets the pages working, though there is a lot more work to do!
=> Add new requisition queries in requisition module

packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx, packages/inventory/src/Stocktake/ListView/ListView.tsx, packages/inventory/src/Stocktake/ListView/Toolbar.tsx, packages/inventory/src/Stocktake/api/hooks.ts, packages/inventory/src/Stocktake/api/index.ts
#847 
- This is just getting the stocktakes list view using the new types and queries/api
=> #847 Stocktake list view using new API

packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx, packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts, packages/inventory/src/Stocktake/DetailView/ContentArea/index.ts, packages/inventory/src/Stocktake/DetailView/index.ts, packages/inventory/src/Stocktake/api/hooks.ts
=> #858 Handling summary items within stocktake columns for item fields

packages/common/src/utils/formatters.ts, packages/inventory/src/InventoryService.tsx, packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx, packages/inventory/src/Stocktake/DetailView/DetailView.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks.ts, packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx, packages/inventory/src/Stocktake/ListView/ListView.tsx, packages/inventory/src/Stocktake/api/api.ts, packages/inventory/src/Stocktake/api/hooks.ts, packages/inventory/src/Stocktake/api/operations.generated.ts, packages/inventory/src/Stocktake/api/operations.graphql, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
Fixes #859 
- Hooks up the create stocktake button again
- Adds navigation through `stocktakeNumber` param
- Adds editable pack size in stocktake line edit
=> #859 Stocktake creation

packages/common/src/intl/locales/en/inventory.json, packages/inventory/src/Stocktake/DetailView/Toolbar.tsx, packages/inventory/src/Stocktake/api/api.ts, packages/inventory/src/Stocktake/api/hooks.ts
Fixes #861 
- Adds stocktake line deletion
=> #861 Stocktake line deletion

packages/common/src/hooks/useDialog/useDialog.tsx, packages/common/src/intl/locales/en/common.json, packages/common/src/intl/locales/en/replenishment.json, packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/RequestRequisition/api/hooks.ts, packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql, packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
Fixes #575 
- Gone with this for now
- The columns of the requisition aren't showing nicely, but will revisit that in another PR
- Note there is a bug with the API where you can't add a requisition line that is in another requisition, I believe - at the moment this won't actually give any feedback
- Also note that there is no `comment` field on the api update input, so comment changes won't persist
=> #575 request req line 3

packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx, packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx, packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
Fixes #901 
- Pretty straight forward next button implementation .. thought it would be more!
=> Add response requisition next button implementation

packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
Fixes #900 
- Another easy one.. not sure why I thought to do these in separate PRs! Nice to have a tight focus though 😁
=> #900 request req next button

packages/common/src/operations.generated.ts, packages/common/src/operations.graphql, packages/common/src/types/schema.ts, packages/dashboard/src/api/operations.generated.ts, packages/dashboard/src/api/operations.graphql, packages/invoices/src/InboundShipment/Dashboard/Widget.tsx, packages/invoices/src/InboundShipment/Dashboard/api.ts, packages/invoices/src/InboundShipment/DetailView/api.ts, packages/invoices/src/InboundShipment/ListView/api.ts, packages/invoices/src/InboundShipment/api/operations.generated.ts, packages/invoices/src/InboundShipment/api/operations.graphql, packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx, packages/invoices/src/OutboundShipment/Dashboard/api.ts, packages/invoices/src/OutboundShipment/ListView/api.ts, packages/invoices/src/OutboundShipment/api/operations.generated.ts, packages/invoices/src/OutboundShipment/api/operations.graphql, packages/system/src/Item/api/api.ts, packages/system/src/Item/api/hooks/useItemListView/useItemListView.ts, packages/system/src/Item/api/operations.generated.ts, packages/system/src/Item/api/operations.graphql, packages/system/src/Location/ListView/api.ts, packages/system/src/Name/ListView/ListView.tsx, packages/system/src/Name/ListView/api.ts, packages/system/src/Name/hooks/useNames.ts
Fixes #905 
- Just stuck to the task and added store IDs to the required queries
=> Add storeIDs to queries

packages/common/src/intl/locales/en/inventory.json, packages/inventory/src/Stocktake/ListView/ListView.tsx, packages/inventory/src/Stocktake/ListView/Toolbar.tsx, packages/inventory/src/Stocktake/api/api.ts, packages/inventory/src/Stocktake/api/hooks.ts
Fixes #860 
- Adds stocktake deletion functionality
- Nothing new I don't think!
=> #860 stocktake deletion

packages/inventory/src/Stocktake/api/hooks.ts, packages/requisitions/src/RequestRequisition/ListView/ListView.tsx, packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/RequestRequisition/api/hooks.ts, packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql, packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx, packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx, packages/requisitions/src/utils.ts
Fixes #867 
- Removes response req deletion UI
- Adds request deletion functionality
=> #867 Requisition deletions

packages/common/src/utils/arrays/utils.ts, packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEdit.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditTable.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/useDraftOutboundLines.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/hooks/usePackSizeController.tsx, packages/invoices/src/OutboundShipment/DetailView/modals/utils.test.ts, packages/invoices/src/OutboundShipment/DetailView/modals/utils.ts, packages/invoices/src/OutboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/operations.generated.ts, packages/invoices/src/OutboundShipment/api/operations.graphql, packages/invoices/src/types.ts
#810 
- Adds mutations for updating/inserting a placeholder row
- Need to also stop the status change when we have unallocated lines
=> Add placeholder row mutation implementation

packages/inventory/src/Stocktake/api/hooks.ts, packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/ListView/ListView.tsx, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/InboundShipment/api/hooks.ts, packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx, packages/requisitions/src/RequestRequisition/ListView/ListView.tsx, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/RequestRequisition/api/hooks.ts, packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql, packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx, packages/requisitions/src/ResponseRequisition/api/hooks.ts
Fixes #920 
- Really the colour should be optimistically updated - on a very slow connection there's a bit of lag. Thought for the beta this is fine and there's plenty other more important things to do!
=> #920 list view color mutation

packages/common/src/ui/layout/tables/columns/types.ts, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonZeroNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts, packages/common/src/utils/NumUtils.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #503 
Prevent inbound pack size and quantity being negative.
The currency input is already preventing me from too much negativity.
=> Inbound item editing validation

packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonZeroNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLinePanel.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #947 - just adds the same as for inbound shipments
=> Validate stocktake line inputs

packages/common/src/api/hooks/useFieldsSelector/useFieldsSelector.ts, packages/common/src/api/hooks/useQuerySelector/useQuerySelector.ts, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/InboundShipment/api/hooks.ts
Starts #931 
- Before I go and add this to all the api files, I wanted to do one and get feedback / see if you had any suggestions / improvements / whatever
=> #931 Query key factory for inbound

packages/requisitions/src/RequestRequisition/DetailView/Toolbar.tsx, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/RequestRequisition/api/hooks.ts, packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql
Fixes #954 
- Straight forward deletion of rows
- Removed some commented out code which was done because of waiting for the API to implement a requisition date field. However apparently it's not needed
=> #954 Delete request requisition lines - A week after this PR was made, the TRUTH was revealed -- [8]

packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
Fixes #942 
- Just hides the control.. the actual logic seems fine.
- Tried another fix to show 'any' when there was a placeholder, but I thought this was better?
=> #942 Pack size controller when only one placeholder - We were SHOCKED at what this bug was doing  -- [9]

packages/invoices/src/OutboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/hooks.ts
Fixes #979 Part1 😁 
- This updates the outbound line mutation so that when setting a lines number of packs to zero, the line is deleted. Otherwise, the update is sent and the API throws and error
- I was also working on inbound and refactored a little bit too much, so thought to do another PR with a different diff
=> #979 Update Outbound line mutations - This changes EVERYTHING -- [11]

packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx, packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx, packages/invoices/src/InboundShipment/DetailView/ContentArea/ContentArea.tsx, packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts, packages/invoices/src/InboundShipment/DetailView/ContentArea/index.ts, packages/invoices/src/InboundShipment/DetailView/DetailView.tsx, packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/InboundShipment/api/hooks.ts, packages/invoices/src/OutboundShipment/DetailView/columns.ts, packages/invoices/src/OutboundShipment/api/hooks.ts
Fixes #979 Part2
- Adds to the mutation to delete any lines which have zero number of packs and also not try to insert lines with no number of packs.
- A bit of moving things around - "`GeneralTab`" to `ContentArea`
- Since I was touching inbound stuff.. the columns weren't sortable so I added that
- Then the outbound column sorting was broken so I fixed that also
- Fixed the inbound list view deletion while I was there also
- Also the cell value setter was having memoise problems so I touched that too
=> #979 Correct line mutations Part 2 - You will never guess what this PR is really doing  -- [12]

packages/common/src/authentication/AuthContext.tsx
Fixes #996 
The store wasn't saved in cookie, and so didn't persist
=> store store in cookie

packages/common/src/types/schema.ts, packages/invoices/src/InboundShipment/api/operations.generated.ts, packages/invoices/src/InboundShipment/api/operations.graphql, packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx, packages/invoices/src/OutboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/operations.generated.ts, packages/invoices/src/OutboundShipment/api/operations.graphql, packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql, packages/requisitions/src/ResponseRequisition/api/operations.generated.ts, packages/requisitions/src/ResponseRequisition/api/operations.graphql, packages/system/src/Item/api/hooks/useItemsList/useItemsList.ts, packages/system/src/Item/api/operations.generated.ts, packages/system/src/Item/api/operations.graphql
Fixes #1003 
A few changes in this one, some more `storeId`s required, item type & `TaxUpdate`
=> Generate & implement API changes

packages/dashboard/src/api/api.ts, packages/dashboard/src/api/operations.generated.ts, packages/dashboard/src/api/operations.graphql, packages/host/src/components/AppDrawer/AppDrawer.tsx, packages/host/src/components/AppDrawer/AppDrawerIcon.tsx, packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/invoices/src/InboundShipment/api/hooks.ts, packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #999 
Though really, this is just a vehicle to pop in a couple of offroads 😁
=> #999 disable ok and next

packages/common/src/intl/locales/en/distribution.json, packages/common/src/intl/locales/en/replenishment.json, packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx, packages/invoices/src/InboundShipment/DetailView/Footer/OnHoldButton.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx, packages/invoices/src/OutboundShipment/DetailView/Footer/OnHoldButton.tsx
Fixes #987 
- Just a quick on hold confirmation!
=> #987 on hold confirmation

packages/common/src/intl/locales/en/distribution.json, packages/host/public/config.js, packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons.tsx, packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx, packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx, packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/index.ts, packages/requisitions/src/ResponseRequisition/api/operations.generated.ts, packages/requisitions/src/ResponseRequisition/api/operations.graphql
Fixes #1009 
- Ooooh I like the `useAlertModal` 😁
=> #1009 warn when no stock to supply

packages/host/src/components/Login/Login.tsx, packages/host/src/components/Login/hooks.ts
Fix #1019 
Starting pretty simple here!
Also -- reset error state (from previous failed login) once new login request begins.
=> #1019 Disable form when login in progress

packages/requisitions/src/RequestRequisition/DetailView/columns.ts, packages/requisitions/src/ResponseRequisition/DetailView/ContentArea.tsx, packages/requisitions/src/ResponseRequisition/DetailView/columns.ts, packages/requisitions/src/ResponseRequisition/api/hooks.ts
Fixes #1023 
Adds sorting using the same approach as requests
=> Response sorting

packages/common/src/intl/locales/en/catalogue.json, packages/common/src/intl/locales/index.ts, packages/system/src/MasterList/DetailView/AppBarButtons.tsx, packages/system/src/MasterList/DetailView/ContentArea.tsx, packages/system/src/MasterList/DetailView/DetailView.tsx, packages/system/src/MasterList/DetailView/SidePanel.tsx, packages/system/src/MasterList/DetailView/Toolbar/Toolbar.tsx, packages/system/src/MasterList/DetailView/Toolbar/index.ts, packages/system/src/MasterList/DetailView/columns.ts, packages/system/src/MasterList/DetailView/index.ts, packages/system/src/MasterList/Service/Service.tsx, packages/system/src/MasterList/api/api.ts, packages/system/src/MasterList/api/hooks.ts, packages/system/src/MasterList/api/operations.generated.ts, packages/system/src/MasterList/api/operations.graphql
Fixes #802 
It might not be great, but it is something!
There's no mutations, so you cannot update the name or comment, or add/remove items.
You can however, copy to the clipboard! and sort columns! so it was totally worth it.
=> Master list detail view

packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx, packages/common/src/ui/components/inputs/Autocomplete/utils.tsx, packages/common/src/ui/components/modals/ListSearch/ListSearch.tsx, packages/system/src/Name/Components/SupplierSearchInput/SupplierSearchInput.tsx, packages/system/src/Name/Components/SupplierSearchModal/SupplierSearchModal.tsx
Fixes #574 
- Not entirely happy but it's something. Just copying mSupply?
=> #574 indicate internal suppliers

packages/common/src/authentication/AuthContext.tsx, packages/common/src/localStorage/keys.ts, packages/host/src/components/Login/Login.tsx, packages/host/src/components/Login/LoginLayout.tsx, packages/host/src/components/Login/hooks.ts, packages/system/src/Store/api/operations.generated.ts, packages/system/src/Store/api/operations.graphql, packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx, packages/system/src/Store/components/StoreSearchInput/index.ts, packages/system/src/Store/components/index.ts, packages/system/src/Store/index.ts
Fixes #941 and #1006 a little bit
- Shifted the store drop down
- Added a default sort to store query - too hacky?
- Getting the name is more annoying - it requires a store ID..
- Then I had an idea and couldn't help myself with `LoginLayout`
=> #941 Shift store drop down

packages/common/src/authentication/AuthContext.tsx, packages/common/src/intl/intlHelpers.ts
Fixes #1037 
- Sets a default language for users to en
=> Add default language

packages/host/src/Host.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks.ts, packages/inventory/src/Stocktake/api/operations.generated.ts, packages/inventory/src/Stocktake/api/operations.graphql
Fixes #1057 
- Also an off-road `isProduction` bug that I added with a PR recently
=> Add default to true when creating a stocktake line from a stockline

packages/common/src/intl/locales/en/common.json, packages/common/src/intl/locales/en/distribution.json, packages/common/src/intl/locales/en/inventory.json, packages/invoices/src/InboundShipment/ListView/Toolbar.tsx, packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx, packages/system/src/MasterList/ListView/Toolbar.tsx
Fix #940 
Just the simple "only search by name" option -- needs back-end changes to filtering to be able to search both comment and name.
=> #940 Search by name (shipments)

README.md, packages/common/src/intl/locales/en/app.json, packages/common/src/utils/testing/testing.tsx, packages/config/src/index.ts, packages/host/public/config.js, packages/host/src/Host.tsx, packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx, packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx, packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx, packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons.tsx, packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx, packages/system/src/Report/api/api.ts, packages/system/src/Report/api/hooks.ts, packages/system/src/Report/api/index.ts, packages/system/src/Report/api/operations.generated.ts, packages/system/src/Report/api/operations.graphql, packages/system/src/Report/components/ReportSelector.tsx, packages/system/src/Report/components/index.ts, packages/system/src/Report/index.ts, packages/system/src/index.ts
Fixes #1067 
Wanted to get something in which would use the stub printing implementation. and this does 😁 
Should be enough to work with the full api implementation when done
I'm not entirely convinced about the popover usage.. though ok for now?
Couple of things not implemented in the API, though they are hooked up in this PR, awaiting implementation:
- sort
- filter by category
=> #1067 printing stub

packages/common/src/intl/locales/en/common.json, packages/common/src/intl/locales/en/distribution.json, packages/common/src/intl/locales/en/inventory.json, packages/common/src/intl/locales/en/replenishment.json, packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx, packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx, packages/requisitions/src/ResponseRequisition/DetailView/RelatedDocumentsSection.tsx, packages/requisitions/src/ResponseRequisition/DetailView/SidePanel.tsx
Fixes #1093 
fwiw I think that 'entered by' is more helpful and I'd prefer if that was returned. Have updated the label anyway so that we're not misleading.
=> Update entered-by label

packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx, packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundDelete.ts
Fixes #1107 
Just needed to update the cache - the cache key was missed in some recent refactoring
=> Refresh outbound list cache on delete

packages/common/src/authentication/AuthContext.tsx, packages/common/src/authentication/api/api.ts, packages/common/src/authentication/api/hooks/useStores.ts, packages/common/src/authentication/api/operations.generated.ts, packages/common/src/authentication/api/operations.graphql, packages/common/src/types/schema.ts, packages/host/src/components/Login/Login.tsx, packages/host/src/components/Login/LoginLayout.tsx, packages/host/src/components/Login/hooks.ts
Fixes #1089 
Does what it says on the tin.
Uses most recently used store, or picks the first one from the (alphabetically sorted) list.
Should probably have waited for the API changes, but what's a little rework amongst friends? 🤷
=> Remove store select from login

packages/requisitions/src/RequestRequisition/api/operations.generated.ts, packages/requisitions/src/RequestRequisition/api/operations.graphql
Fixes #1153 
Oopsie 🙄 
A test is the [internal order #12 in Opua](http://localhost:3003/replenishment/internal-order/12)
=> add typename

packages/common/src/authentication/api/api.ts, packages/common/src/authentication/api/operations.generated.ts, packages/common/src/authentication/api/operations.graphql, packages/common/src/types/schema.ts
Seems to be working and compiles :)
@mark-prins -- in "operations.generated.ts", the `AuthTokenQuery` type updated automatically when I ran the codegen, but `query authToken` in the same file I had to update manually. Is this what's supposed to happen?
Anyway, please modify this as you see fit and merge it as soon as you're happy, since we need to get this working again ASAP. 
You probably want to re-merge main into your Database Queries branch too once this is merged, as it looks like they may have some slight overlap?
=> Quick fix for API authentication changes

packages/common/src/intl/locales/en/app.json, packages/common/src/styles/theme.ts, packages/host/src/components/Login/LoginIcon.tsx, packages/host/src/components/Login/LoginLayout.tsx
Fixes #1148 
Made the font sizes responsive - after realising that simply making font sizes `rem`s does not help with this little problem. We can change them later to rems, that's a different concern to this problem
=> Update login style

packages/common/src/api/GqlContext.tsx, packages/common/src/authentication/AuthContext.tsx, packages/common/src/authentication/api/api.ts, packages/common/src/authentication/api/hooks/useUserDetails.ts, packages/host/src/QueryErrorHandler.tsx, packages/host/src/components/AuthenticationAlert.tsx, packages/inventory/src/Stocktake/api/api.ts, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/api.ts, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/ResponseRequisition/api/api.ts
Fixes #1163 
I've removed the 'create/edit requisition' permission from the user `Kopu` : if you login as them and try to create or edit a requisition you'll get a modal, as well as the toast notification:
=> #1163 permission errors

packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Fixes #1036 
Seemed reasonable, so I've changed. Raised an issue for the API which appears incorrect: https://github.com/openmsupply/remote-server/issues/1017
=> Change column source

packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/CommentPopoverColumn.tsx, packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/index.ts, packages/common/src/ui/layout/tables/columns/index.ts, packages/host/src/CommandK.tsx, packages/host/src/Site.tsx, packages/requisitions/src/RequestRequisition/DetailView/columns.ts, packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Fixes #577 
Changed to the speech bubble comment style
=> #577 speech bubble comment

packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx, packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx, packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMultiList.tsx, packages/common/src/ui/components/inputs/Autocomplete/index.ts, packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx, packages/system/src/Item/Components/StockItemSelectModal/StockItemSelectModal.tsx
Fixes #1126 
Extracted out the component, used it in the stocktake creation modal and created a story for it.
=> Create multi option autocomplete list

packages/common/src/intl/locales/en/app.json, packages/common/src/intl/locales/en/inventory.json, packages/common/src/intl/locales/en/replenishment.json, packages/common/src/ui/components/navigation/Tabs/TabKeybindings.tsx, packages/common/src/ui/components/navigation/Tabs/Tabs.tsx, packages/common/src/ui/components/navigation/Tabs/index.ts, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTabs.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockEvolution.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
Fixes #1181 
Some more usability items raised by Richard
=> Usability: 4

packages/common/src/api/GqlContext.tsx, packages/common/src/authentication/api/api.ts, packages/common/src/intl/locales/en/common.json, packages/common/src/ui/components/popover/PaperPopover/PaperPopoverSection.tsx, packages/dashboard/src/api/api.ts, packages/dashboard/src/widgets/StockWidget.tsx, packages/host/src/QueryErrorHandler.tsx, packages/invoices/src/InboundShipment/Dashboard/Widget.tsx, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx, packages/invoices/src/OutboundShipment/api/api.ts, packages/system/src/Name/api/api.ts, packages/system/src/Report/api/api.ts, packages/system/src/Report/api/hooks.ts, packages/system/src/Report/components/ReportSelector.tsx
Fixes #1185 
Checking for undefined responses mainly - also not toasting when the user is logged out, since that is handled by the Auth Modal
=> 1185 permission issues

.github/workflows/bumpr.yaml
=> commit test

packages/inventory/src/Stocktake/api/api.ts, packages/invoices/src/InboundShipment/api/api.ts, packages/invoices/src/OutboundShipment/api/api.ts, packages/requisitions/src/RequestRequisition/api/api.ts, packages/requisitions/src/ResponseRequisition/api/api.ts, packages/system/src/Item/api/api.ts, packages/system/src/Location/api/api.ts, packages/system/src/MasterList/api/api.ts, packages/system/src/Stock/api/api.ts
Fixes #1197 
The client part anyway - there's an issue with the server allowing authentication when I believe it shouldn't. See https://github.com/openmsupply/remote-server/issues/1061 for status on that one.
In this PR, have removed all of the additional errors, and therefore error toasts, that Bijay was observing. Now, from a client point of view, things are behaving rationally - the only extra step is preventing the login.
=> Handle undefined data

packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeIntegerInput.tsx, packages/common/src/ui/components/inputs/TextInput/numeric/index.ts, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeIntegerCell.tsx, packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts, packages/common/src/utils/numbers/NumUtils.ts, packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx, packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx, packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx, packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts, packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx, packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx, packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
Fixes #1201 Might have closed the previous PR accidentally?
=> 1200 outbound real problems

packages/common/src/intl/locales/en/distribution.json, packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx, packages/inventory/src/Stocktake/api/api.ts, packages/inventory/src/Stocktake/api/hooks.ts
Fixes #1208 
Not very happy with the concept - went with it because
- it makes viewing stocktake in mSupply happier
- allows for localisation of the default description
- makes the list view look nicer
but.. 🤷 
Ideally we'd create the default on the server, but wasn't sure that could have translated / localised versions of the text if we did that
=> Add default stocktake description

packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
Fixes #1207 
Adds a little validation when creating locations
=> Form validation for location

packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
Fixes #970 
Only found one instance left, after the recent updates to add the `NonNegativeIntegerInput` component.
=> Limit internal order quantity

jest.config.js, package.json, packages/common/src/ui/components/errors/NothingHere.tsx, packages/common/src/utils/arrays/ArrayUtils.test.ts, packages/common/src/utils/arrays/SortUtils.test.ts, packages/common/src/utils/formatters/formatters.test.ts, packages/common/src/utils/numbers/NumUtils.test.ts, packages/common/src/utils/regex/RegexUtils.test.ts, yarn.lock
Fixes #1050 
Adds a few tests for the utils
=> 1050 utils tests

packages/common/src/intl/context/IntlContext.tsx, packages/common/src/intl/context/browserLanguageDetector.ts
Fixes #1232 
Have taken the i18next navigator detection and tweaked to remove the region. Fixes the problem for me in firefox
=> Custom language detection

packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java, packages/android/app/src/main/java/org/openmsupply/client/RemoteServer.java, packages/android/app/src/main/java/org/openmsupply/client/certplugin/CertPlugin.java
Adds a plugin to allow https connections to the local remote server
Related: https://github.com/openmsupply/remote-server/pull/1086
=> Android https

README.md, package.json, packages/android/app/build.gradle
I used to the local.properties file for configuring the keystore params. Could also be changed to let the user enter the password on the cli...
Closes #1246
=> Android release build
