packages/dashboard/tsconfig.json
packages/host/tsconfig.json
packages/transactions/.swcrc
packages/transactions/package.json
packages/transactions/public/index.html
packages/transactions/src/App.tsx
packages/transactions/src/TransactionService.tsx
packages/transactions/src/bootstrap.tsx
packages/transactions/src/index.ts
packages/transactions/tsconfig.json
packages/transactions/webpack.config.js
yarn.lock

Fixes #12  - kind of
- Aim was to get HMR 'working'. This only works when you are working on the standalone MFE. I.e. if we run this branch and go to `localhost:3005` - HMR is working, but it wouldn't work if I had a `TransactionService` imported into `Host`- the `TransactionService` wouldn't auto-replace.
- I think this isn't ideal but it is still useful. I could see us developing the 'main container' - i.e. with the appbar and top bar as components, and the `transactions` MFE could use that container as it's primary app, so that when you're developing transactions, you just use the specific url for that MFE. I think there's issues when a MFE starts utilizing other MFE's, though ..
- I chose `transactions` because the ui designs and also the backend team seem to be looking at customer …

#12 Transaction MFE + Hot replacement

---

packages/common/src/hooks/index.ts
packages/common/src/hooks/useDrawer.ts
packages/common/src/hooks/useLocalStorageSync.ts
packages/common/src/ui/components/NavLink.tsx
packages/common/src/ui/components/index.ts
packages/customers/src/CustomerContainer.tsx
packages/customers/src/Nav.tsx
packages/customers/src/types.d.ts
packages/customers/webpack.config.js
packages/host/src/AppDrawer.tsx
packages/host/src/Host.tsx
packages/host/src/types.d.ts
packages/transactions/src/TransactionService.tsx

Fixes #36
This is adding the customer navigation to the app drawer
Thought this was enough for the PR for now. Some things in new PRs
- The drawer state is not correctly shared and can get munged. Need to essentially share the state between all `useDrawer` hook usages. Few options here
- Similar to the drawer state, the 'title' needs to be updated better. Can continue using the service context that's in the host package, however that will cause a re-render of the whole app which isn't ideal and I think a solution for both the drawer and title could be used.
- Breadcrumbs - a bit annoying to do this one but likely going to be a similar state that needs to be updated from many different places, same as the above two
- Styling: Not looking correct right now
- 'selected state' - need an …

#36 customer package navigation

---

package.json
packages/common/src/intl/IntlTestProvider.tsx
packages/common/src/intl/locales/en.json
packages/common/src/styles/index.ts
packages/common/src/styles/theme.ts
packages/common/src/ui/components/NavLink.tsx
packages/common/src/ui/components/buttons/styles.ts
packages/common/src/ui/icons/MSupplyGuy.tsx
packages/common/src/utils/testing.tsx
packages/customers/src/Nav.tsx
packages/host/src/AppDrawer.stories.tsx
packages/host/src/AppDrawer.test.tsx
packages/host/src/AppDrawer.tsx
packages/host/src/Viewport.tsx
yarn.lock

Partial fixes #81 
- Fixes the storybook problem, which was that when I upgraded to v5 mui, the dependency of `emotion` that storybook and mui were out of sync, causing issues which made me very angry and sad and happy. This is why there are deps added for `emotion` and the resolution to a specific version. This was to my main goal which I originally thought was because of the `makeStyle` uses which I was hoping I was going to kill 3 birds with one stone (storybook/rtl/extra package). Nope
- Removed use of `makeStyle` in `AppDrawer` and `NavLink`. I ran in to a few learning curves
- We can't pass arbitrary props to dom elements like a `div` or `a`, so when using `Styled`, you sometimes have to use `shouldForwardProps` to stop the propagation of that prop.
- Overriding mui classes ends up …

#81 remote some make styles

---

packages/config/src/index.ts
packages/host/package.json
packages/host/public/config.js
packages/host/public/index.html
packages/host/webpack.config.js
packages/mock-server/package.json
packages/transactions/src/OutboundShipment/DetailView.tsx
packages/transactions/src/OutboundShipment/ListView.tsx
yarn.lock

Fixes #122 
Adds the option to override environment based settings at runtime. Possibly the API url will just be on the same url with a specific port and we won't need this for production, instead a version which overrides for local dev. Not sure at this stage - this option allows the same code to run in different environments, so meets my need.
Also tidied the 'production' mode which wasn't being set when a build was run.

production build

---

.gitignore
packages/common/src/ui/components/buttons/NavigationButton.tsx
packages/common/src/ui/components/buttons/index.ts
packages/common/src/ui/icons/Invoice.tsx
packages/common/src/ui/icons/index.ts
packages/customers/src/CustomerContainer.tsx
packages/dashboard/src/DashboardService.tsx
packages/host/src/AppDrawer.tsx
packages/host/src/Host.tsx
packages/mock-server/src/schema/Transaction.js

Fixes #119 
Few small tidies and helpers:
- changed the page placeholder text to simply say `[ Placeholder page: xxxxx ]`
- fixed an issue with the left nav: if the screen size is small then the bottom options disappear. The upper section now is scrollable with the bottom section always shown, and always at the bottom
- Added some buttons to the customers page, when the drawer is collapsed you couldn't get to the list page
- removed the delay on the mock server response 🤷‍♂️

#119 placeholders

---

packages/common/src/styles/theme.ts
packages/common/src/ui/components/inputs/Checkbox/Checkbox.stories.tsx
packages/common/src/ui/components/inputs/Checkbox/Checkbox.tsx
packages/common/src/ui/components/inputs/Checkbox/index.ts
packages/common/src/ui/layout/tables/RemoteDataTable.tsx
packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
packages/common/src/ui/layout/tables/columns/index.ts
packages/common/src/ui/layout/tables/hooks/index.ts
packages/common/src/ui/layout/tables/hooks/useColumns.ts
packages/common/src/ui/layout/tables/hooks/useDataTableApi.ts
packages/common/src/ui/layout/tables/index.ts
packages/common/src/ui/layout/tables/types.ts
packages/config/src/index.ts
packages/host/src/Host.tsx
packages/transactions/src/OutboundShipment/ListView/ListView.tsx
types/react-table-config.d.ts

#128 partly - enough for now
- I went with a quick implementation with the `useImperativeHandle` hook to see if we like it. It's against the 'react grain' (passing props down, rather than passing a thing down to access the child) so I can see it not being liked. I am still undecided
- couple offroads
- Think best to change the icons of the checkbox for the nice border radius (which I played with and cant get to work) and color. Probably better to be using the blue as the secondary, I guess

#128 add row select mechanism

---

packages/common/src/hooks/useHostContext.ts
packages/common/src/ui/components/index.ts
packages/common/src/ui/components/inputs/Dropdown/Dropdown.tsx
packages/common/src/ui/components/inputs/Dropdown/index.ts
packages/common/src/ui/components/inputs/index.ts
packages/common/src/ui/components/portals/AppBarContent.tsx
packages/common/src/ui/components/portals/AppBarContent/AppBarContent.test.tsx
packages/common/src/ui/components/portals/AppBarContent/AppBarContent.tsx
packages/common/src/ui/components/portals/AppBarContent/index.ts
packages/common/src/ui/components/portals/index.ts
packages/common/src/ui/layout/tables/hooks/useDataTableApi.ts
packages/common/src/ui/layout/tables/types.ts
packages/host/src/AppBar.tsx
packages/transactions/src/OutboundShipment/ListView/ListView.tsx

Fixes nothing!
- I renamed the abbbar ref
- I made a `portals` folder with the intention that we can make portal 'pair' components and have the 'source' rendered somewhere and then we just need to wrap some content in `<AppbarContentPortal>` which is neat and potentially OTT
- I put a select in a `Dropdown` file which is super helpful. Looking to style it later. Also why did I name it `Dropdown`?
- Also added some methods to the `tableApi` ref and it was at this point I started googleing. Then I found this issue: https://github.com/tannerlinsley/react-table/issues/2459 and decided that we were going to need to a different approach for managing the 'table state' outside of `react-table` itself (i.e. to have a checkbox above the `table` component in the dom tree).
- I basically want to …

#140 listview actionbar

---

packages/common/src/ui/components/menus/ColorMenu/ColorMenu.stories.tsx
packages/common/src/ui/components/menus/ColorMenu/ColorMenu.test.tsx
packages/common/src/ui/components/menus/ColorMenu/ColorMenu.tsx
packages/common/src/ui/components/menus/ColorMenu/index.ts
packages/common/src/ui/components/menus/index.ts
packages/common/src/ui/icons/Circle.tsx
packages/common/src/ui/icons/Icon.stories.tsx
packages/common/src/ui/icons/index.ts

Partial #149 
- Adding just the color menu component and a circle svg (I used american spelling - thought `<ColourMenu color="x"/>` was a bit weird 
- although this features seems lower in priority, I thought doing this would give me some insight into doing mutations with the data table
- I think it did! 
- Need to pass a callback from `ListView`, down to the `Cell` level - i.e. `changeTransactionColor`.
- On mobile, we do this by passing a `getCallback` function to `DataTableRow`, which the `Row` calls and passes to the `Cell`, depending on the `CellKey`.
- With our current setup, we can pass into the `column` object passed into `useColumns` the callback for that column which does seem simpler

#149 color column

---

packages/common/package.json
packages/common/src/hooks/useDraftDocument/types.ts
packages/common/src/hooks/useDraftDocument/useDraftDocument.ts
packages/common/src/index.ts
packages/common/src/ui/layout/tables/RemoteDataTable.tsx
packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/components/Header/Header.stories.tsx
packages/common/src/ui/layout/tables/components/Header/Header.test.tsx
packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/common/src/ui/layout/tables/hooks/useColumns.tsx
packages/common/src/ui/layout/tables/types.ts
packages/mocks/src/handlers.ts
packages/transactions/src/OutboundShipment/DetailView/DetailView.tsx
packages/transactions/src/OutboundShipment/DetailView/reducer.ts
packages/transactions/src/OutboundShipment/DetailView/tabs/GeneralTab.test.tsx
packages/transactions/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/transactions/src/OutboundShipment/DetailView/types.ts
packages/transactions/src/OutboundShipment/ListView/ListView.tsx
yarn.lock

Fixes #193 
Combining a few things here
- Putting the state of sorting for the detail view in the reducer. The `useSortedData` hook was a problem as it was difficult to keep the sort stable after an edit .. (needed to memoize to keep the data sorted, but if you don't memoize, editing values caused a re-sort..).
- Added `immer`. The reducer is much more readable now. Went with using `immer` and `produce` over using the `use-immer` package with `useImmerReducer` because I added the hook and then had some type problems and saved more time by not using the hook 🤷 
- I put the `sortBy` object and `onChangeSortBy` into the `useColumns` hook. I think this works pretty nicely, the `Column` is the active object for the table and `ColumnDefinition` is just that. Saves prob drilling and makes a …

#225 reducer to handle sorting

---

packages/common/src/intl/intlHelpers.ts
packages/common/src/ui/components/StatusCrumbs.stories.tsx
packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/hooks/useColumns.tsx
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/invoices/src/OutboundShipment/DetailView/types.ts

Fixes #289 
Added the columns and in the process got a little frustrated with the nested API response. This won't work with the current way we have the key in the accessor, so I've flattened the data for now.
Also popped in currency formatting.. that should probably pick up INTL format from somewhere, which doesn't exist yet
.

add some columns

---

packages/common/src/hooks/index.ts
packages/common/src/hooks/useContentAreaHeight/index.ts
packages/common/src/hooks/useContentAreaHeight/useContentAreaHeight.test.tsx
packages/common/src/hooks/useContentAreaHeight/useContentAreaHeight.tsx
packages/common/src/hooks/useListData/useListData.ts
packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
packages/common/src/hooks/useQueryParams/useQueryParams.ts
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/types.ts
packages/host/src/Host.tsx
packages/host/src/Viewport.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/system/src/Customer/ListView/ListView.tsx
packages/system/src/Item/ListView/ListView.tsx

Oh, smaller than I thought..! Nice suprise
- I am in the process of adding expanding to the rows, which means we need scroll.
- I had a bit of rough time with this of course, trying to have a flex table which when overflowing, horizontally and vertically scrolls.
- I've gotten there with the scrolling (You can just duplicate columns to see the column scroll - I think some of our columns have minWidths which are too small, though) however I've made the headers non-sticky, now. I've played around with mui `stickHeader` and also apparently you can put `position:'sticky'` on the `td` for a header, however it doesn't seem to work with `display:'flex'` on the header cells. Sigh!
- I spent way too much time messing with this so I've stopped here with the messed up headers which I will come back …

6 - #311 group by batch 1

---

packages/common/src/hooks/useQueryParams/useQueryParams.ts
packages/common/src/intl/locales/ar.json
packages/common/src/intl/locales/en.json
packages/common/src/intl/locales/fr.json
packages/common/src/intl/locales/pt.json
packages/common/src/ui/icons/ChevronsDown.tsx
packages/common/src/ui/icons/Icon.stories.tsx
packages/common/src/ui/icons/index.ts
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
packages/common/src/ui/layout/tables/columns/RowExpand/RowExpand.tsx
packages/common/src/ui/layout/tables/columns/RowExpand/index.tsx
packages/common/src/ui/layout/tables/columns/index.ts
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/context/TableContext.test.ts
packages/common/src/ui/layout/tables/context/TableContext.ts
packages/common/src/ui/layout/tables/types.ts
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx

I messed up commits - whoops.
First one is https://github.com/openmsupply/openmsupply-client/pull/349 - Accidentally committed to that branch *and* pushed, so took an earlier commit and made that PR.
----------
This one introduces row expanding
- It's in the `TableContext` which made this quite easy
- I used chevron because the plus looked strange, then I googled and it said use chevron for accordions - the double chevrons.. uh.. maybe not..
- The content is just placeholder
- I am fairly convinced that using an accordion for rows AND a modal is too much - I don't see why we need both (and now have a preference for the accordion...)

5 - #311 group by batch

---

packages/common/src/ui/layout/tables/hooks/useColumns.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/index.ts
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.test.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts

Fixes #331 
- Goal was to ensure the default column alignment took into account the format
- Then I offroaded into extracting the logic of `useColumns` into a function and just having the hook basially memoise and call this function. This is because I have been meaning to do this for a bit, as it makes some tests easier to write, in some cases - so I updated the reducer test cases
- Then I added some tests for `useColumns`

#331 column format default

---

packages/common/src/ui/layout/tables/components/Header/Header.tsx

Fixes #326 
Went this route because I don't think a column should ever be not sortable - even though there is a slight lag when pressed

Add debounced column sorting

---

packages/common/src/operations.graphql
packages/common/src/schema.graphql
packages/common/src/types/index.ts
packages/common/src/types/schema.ts
packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/mock-server/src/data/data.ts
packages/mock-server/src/data/types.ts
packages/system/src/Item/ListView/ListView.tsx

This is the last of the query shifting.
This has ended up being so much bigger than I thought, sorry.
From here I would like to:
1. Create a more common way of creating the sdk/api object. I am thinking to make a `context` which the host can create the `sdk/api` object on load, and then each package can use a `useApi` hook. This also has the added bonus of allow the host to inject the credentials into the `api` object so each package doesn't need to worry about it (also the URL)
2. Sort the sorting out. I think if I get to it soon, I'm just going to add a `sortKey` to the `column` - I don't want to wait..
3. Organise the different enums and use them a bit better in our code - i.e. the statuses
4. Sort the mapping out. I'm sure there's a better pattern to be using here to map things, …

Add item query to use code gen

---

packages/common/src/hooks/useDocument/types.ts
packages/common/src/hooks/useDocument/useDocument.ts
packages/common/src/hooks/useListData/useListData.test.tsx
packages/common/src/hooks/useListData/useListData.ts
packages/common/src/operations.graphql
packages/common/src/types/index.ts
packages/common/src/types/schema.ts
packages/host/src/bootstrap.tsx
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/ListView/api.ts
packages/invoices/src/api.ts
packages/system/src/Customer/ListView/ListView.tsx
packages/system/src/Customer/ListView/api.ts
packages/system/src/Item/ListView/ListView.tsx
packages/system/src/Item/ListView/api.ts

Fixes #368 
*Sigh* cool diff..
Wondering what you think of this...
I wanted to make some sort of generic transformer which gets rid of all the 'nodes' but it ended up being way to messy. So went with the simpler duplicate a bunch of stuff approach..
currently if you have an error in one the guarded fields, an error is thrown - i.e.
```
context.data({
invoices: {
...result,
error: { description: 'Error!' },
__typename: 'NotInvoiceConnector',
},
})
```
will show "no records found" with a toast of the description..
I think it needs more work, handling all the different errors, but if there are errors in any of these guarded fields, I think   there's basically a big fuck up..

#368 map gql returns

---

packages/common/src/ui/layout/tables/components/Header/Header.test.tsx
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/ListView/api.ts
packages/mock-server/src/api/resolvers.ts
packages/mock-server/src/data/types.ts
packages/mock-server/src/schema/Invoice.ts
packages/mock-server/src/schema/Item.ts
packages/mock-server/src/schema/Name.ts
packages/mock-server/src/worker/handlers.ts
packages/system/src/Customer/ListView/ListView.tsx
packages/system/src/Item/ListView/ListView.tsx

Fixes #367 
- This aligns with the backend sorting
- I've just made it so we map the sort key to the enum of what the backend provides in the api layer. I was going to add a `sortKey` to the column, but then I would need to add another generic to a bunch of stuff which defines the set of sort keys, and then also we would have the client side sorting needing to use different types.. I figured to just do this, which isn't as 'safe' in terms of ensuring that a columns sort key is guaranteed to be sortable but is simpler and easier, I think

#367 sort out sorting

---

packages/common/src/hooks/useDetailPanel.tsx
packages/common/src/hooks/useIsScreen/index.ts
packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.test.ts
packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.ts
packages/common/src/hooks/useIsScreen/useIsLargeScreen.test.ts
packages/common/src/hooks/useIsScreen/useIsLargeScreen.ts
packages/common/src/hooks/useIsScreen/useIsMediumScreen.test.ts
packages/common/src/hooks/useIsScreen/useIsMediumScreen.tsx
packages/common/src/hooks/useIsScreen/useIsScreen.ts
packages/common/src/hooks/useIsScreen/useIsSmallScreen.test.ts
packages/common/src/hooks/useIsScreen/useIsSmallScreen.ts
packages/common/src/styles/theme.ts
packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
packages/common/src/ui/components/domain/StatusCrumbs/StatusCrumbs.tsx
packages/invoices/src/OutboundShipment/DetailView/Footer.tsx

Fixes #389 
- Made the buttons shrink slightly earlier
- Went off road and made the status crumb component just a single crumb when the screens too small:
which is trying to handle this situation
(And as I look at this, I notice we will need to also sort out the normal breadcrumbs for when we add the invoice number)
Not ideal, but more ideal than taking more vertical space by adding even more to the footer

#389 make buttons responsive

---

packages/common/src/hooks/useFilterBy/index.ts
packages/common/src/hooks/useFilterBy/useFilterBy.test.tsx
packages/common/src/hooks/useFilterBy/useFilterBy.tsx
packages/common/src/hooks/useListData/useListData.test.tsx
packages/common/src/hooks/useListData/useListData.ts
packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
packages/common/src/hooks/useQueryParams/useQueryParams.ts
packages/common/src/hooks/useSortBy/useSortBy.ts
packages/common/src/operations.graphql
packages/common/src/schema.graphql
packages/common/src/types/schema.ts
packages/dashboard/src/widgets/OutboundShipmentsWidget.tsx
packages/host/public/config.js
packages/host/src/AppDrawer.test.tsx
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
packages/invoices/src/OutboundShipment/ListView/api.ts
packages/mock-server/src/api/resolvers.ts
packages/mock-server/src/schema/Invoice.ts
packages/system/src/Item/ListView/ListView.tsx
packages/system/src/Name/ListView/ListView.tsx

Fixes #327 - or starts
- Added a `useFilterBy` hook to help with filtering. I was really unsure of the api for this hook and the types are still struggling
- Added a small text box in the outbound shipment area for filtering to test this out - will build on that to make a better ui, which i have no idea what it would look like - but will add debouncing etc etc

#327 add filtering

---

packages/common/src/operations.graphql
packages/common/src/types/index.ts
packages/common/src/types/schema.ts
packages/host/src/bootstrap.tsx
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts
packages/invoices/src/OutboundShipment/DetailView/reducer.ts
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.test.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/invoices/src/OutboundShipment/DetailView/types.ts
packages/invoices/src/api.ts
packages/mock-server/src/api/mutations.ts
packages/mock-server/src/data/database.ts
packages/mock-server/src/schema/Invoice.ts
packages/mock-server/src/schema/invoiceLine.ts
packages/mock-server/src/worker/handlers.ts

Bit big!
- Extremely tedious and frustrating without the real api but this adds inserting of invoice lines using the extracted schema......
- It's 'working' for both the mock server and mock worker (persisting, at least)
- There are a bunch of updates still needed, but thought to PR this for now as it's getting too big
- There are values which when added show in the table as `null`/`undefined` - i.e. for `batch` which 1) likely need values added and 2) need to handle this better in cells, probably
- You can only add a single line at a time, at the moment as the `id` given in `ItemDetailsModal` is always `""`, and so when updating/inserting lines we insert with id `""` and then update id `""`. Will add a `uuid` package to generate these in the next one
- Not handling the response right now …

#273 mutations 5

---

packages/common/src/hooks/index.ts
packages/common/src/operations.graphql
packages/common/src/types/index.ts
packages/common/src/types/schema.ts
packages/common/src/ui/forms/Modal/ModalInput.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/invoices/src/OutboundShipment/DetailView/reducer.ts
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/mock-server/src/api/resolvers.ts
packages/mock-server/src/schema/Item.ts
packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.stories.tsx
packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx
packages/system/src/Item/hooks/useItems/useItems.ts

Working on #293 ..
- So, we need to edit a row which means we need to set that row as the 'selected row' at some higher level than the modal. This PR lifts the state of the 'selectedItem' in the modal to be at the `DetailView` level. Which means that the `DetailView` passes a callback to change the selected item, also.
- In addition, instead of passing an `InvoiceLine`, we need to have the modal work on all `InvoiceLine`s of an item within the invoice, so have adjusted the modal to work with a `SummaryItem`.
With these changes, a couple of challenges:
- When passing the `SummaryItem`, we have access to the invoice lines, but not the `StockLine`s (In addition, we have the item name, code and ID, but not the actual item - however, it's not needed). I thought of a few solutions: Put the …

#293 editable rows

---

packages/common/src/intl/locales/ar.json
packages/common/src/intl/locales/en.json
packages/common/src/intl/locales/fr.json
packages/common/src/intl/locales/pt.json
packages/common/src/operations.graphql
packages/common/src/types/index.ts
packages/common/src/types/schema.ts
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/common/src/ui/layout/tables/types.ts
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/SidePanel.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/invoices/src/OutboundShipment/DetailView/reducer.test.ts
packages/invoices/src/OutboundShipment/DetailView/reducer.ts
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx
packages/invoices/src/api.ts
packages/mock-server/src/api/mutations.ts
packages/mock-server/src/data/database.ts
packages/mock-server/src/schema/Invoice.ts
packages/mock-server/src/worker/handlers.ts

#273 
- finally?!
- This one makes editing lines work! It's working well against the mock server and workers
- There are still a few issues with available quantity I will point out in comments.
- I've noticed a bug with deleting (where deleting isn't deleting everything) which i'll fix elsewhere
- I've also had a bug a few times with an invalid stock line against the mock server and also once where there was an invalid quantity deduction. I checked my payload and all of the values sent seem to be correct, so I believe this is more about server errors so I am ignoring, for now (I also couldn't find a reliable replication, if you happen to find one I would like to fix the server regardless).
- At the moment, we are sending all lines per save as an update regardless of if they've been …

#273 upsert items

---

packages/common/src/intl/locales/ar.json
packages/common/src/intl/locales/en.json
packages/common/src/intl/locales/fr.json
packages/common/src/intl/locales/pt.json
packages/common/src/ui/components/buttons/FlatButton.tsx
packages/common/src/ui/components/index.ts
packages/invoices/src/OutboundShipment/DetailView/modals/BatchesTable.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/invoices/src/OutboundShipment/DetailView/types.ts

There's a bit going on here!
- Updated the FEFO UI bit. Think it looks OK?
- Made the allocation add rather than replace
- filtered out the invalid pack sizes from the pack size selection
- made placeholder in unit quantity? Though, the column header says # packs so maybe not a good idea.. or can put pack size 1? I dunno...
- added an `allocated` field - dunno if it's useful.
- changed the sort order a bit - I was getting confused when FEFO allocating 🤣  so I put the on hold rows at the top of the invalid area (and a divider between) and then the zero stock ones underneath 🤷 
- Made the headers sticky and added some heights cause the height changing so much was annoying me? Though, it's still not exactly right?
- added a loading indicator for the batches table
- Also changed the field …

#314 improved fefo UI

---

packages/common/src/ui/components/index.ts
packages/common/src/ui/icons/PlusCircle.tsx
packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx
packages/invoices/src/types.ts

This is adding a search input, some item fields and a table to the inbound edit item modal.
It's very loosey goosey right now. I wanted to get it in to have something concrete to show so we can determine whats best to do with the large amount of editable fields on an inbound row v the outbound rows.
Some options I can see:
- Just Scroll
- Tabs - i.e. `general`, `pricing`, `weights`, `discrepancies` `totals`
- 'Tabs' but actually they just scroll to the columns related to the above
- expando
- keep only general details in the table, click on a row and some 'detail' area shows up elsewhere to edit other things
- 1 row per modal and don't use the table [I find this to be least preferable so we can be more consistent 🤷 ]
- use some sort of 'card' in the area for each row, and have the modal …

#448 inbound line adding 2

---

packages/common/src/intl/locales/en/common.json
packages/host/src/routers/InventoryRouter.tsx
packages/system/src/Stock/Components/Toolbar.tsx
packages/system/src/Stock/Components/index.ts
packages/system/src/Stock/ListView/ListView.tsx
packages/system/src/Stock/ListView/api.ts
packages/system/src/Stock/ListView/index.ts
packages/system/src/Stock/Service/Service.tsx
packages/system/src/Stock/Service/index.ts
packages/system/src/Stock/index.ts
packages/system/src/Stock/types.ts
packages/system/src/index.ts

Fixes #416 
Decided not to export to excel at this stage. Also the query endpoint isn't ideal since I have to filter out for zero stock items. for now, I've reused the `getStockListViewApi` call and have just asked for 1000 rows, then filtered and sorted manually in the `ListView`. Means that it only has to query once and still supports pagination and sorting.

#475 stock list 2

---

packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx
packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx

Fixes #406 
- Can't do `not` on a filter, so doing it in JS
- I quite like the added `extraFilter` prop anyway. Think it'll come in handy.
- Don't like the prop drilling of the draft

#406 filter out items

---

packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx

Fixes #482 
Yes, not worth a whole PR 🙄 
Small offroad to resolve the warning `Warning: Received `false` for a non-boolean attribute `dense`.` which came in with the `DataTable` change

#482 sort pack sizes

---

packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx

Fixes #456 
Quick one to disable OK & Next if the user is editing the only item. I know you said to make the button act as OK, but thought that was misleading, since there is no 'next' to go to 🤷

#456 ok next weird

---

packages/common/package.json
packages/common/src/intl/locales/en/common.json
packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.stories.tsx
packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
packages/common/src/ui/components/inputs/CurrencyInput/index.ts
packages/common/src/ui/components/inputs/SearchBar/SearchBar.stories.tsx
packages/common/src/ui/components/inputs/index.ts
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/columns/LineLabel/LineLabel.tsx
packages/common/src/ui/layout/tables/columns/LineLabel/index.ts
packages/common/src/ui/layout/tables/columns/index.ts
packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/index.ts
packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts
packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
packages/common/src/ui/layout/tables/components/Cells/index.ts
packages/common/src/ui/layout/tables/components/DataRow/DataRow.stories.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.test.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/host/package.json
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit.tsx
yarn.lock

Was getting a bit big. Thought I'd stop here!
- I removed all the unsupported fields and therefore tabs - only leaving the batch and pricing tabs since they needed rewriting anyway, no point having commented & also wrong code
- Added a numeric input and currency input. For the currency I used a currency input package. This is wrapped and exported from common so if we want to remove it we can pretty easily (though maybe I should have no extended the props of the packaged component) - I know how annoying currency can be and so it saved a little bit of time and the result I think is pretty nice. 
- Made the inputs inputable - though they're only editable for newly added rows, for now (the new rows are given the updater function, passed in rows aren't, yet).
- I played a bit with some …

#448 inbound line edit 7

---

packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/index.tsx

Fixes #515 
A small tidy - the span needs to be a block element in order to have a defined width, which is required for overflow. When it takes the width from the `td` that's the full width, and the available is less the padding, so have manually adjusted. Not great, but working ok.

basic cell text overflow

---

packages/common/src/operations.graphql
packages/common/src/schema.graphql
packages/common/src/types/schema.ts
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
packages/inventory/src/Stocktake/DetailView/api.ts
packages/inventory/src/Stocktake/DetailView/reducer.ts
packages/inventory/src/Stocktake/ListView/ListView.tsx
packages/inventory/src/types.ts
packages/inventory/src/utils.ts
packages/mock-server/src/data/data.ts
packages/mock-server/src/data/database.ts

Fixes #600 
- Just adds an `enteredByName` and `entryDatetime` fields which should correspond to `stock_take_created_date` and `created_by_ID` fields currently in mSupply
- Also offroaded a rename of `stocktakeDate` -> `stocktakeDatetime`
- Also removed the related documents section. Maybe could have put the inventory adjustments created here? Unsure. Mainly removed this in hopes someone would have ideas of what else to put in here!

#600 stocktake entry and entered date fields

---

packages/common/src/intl/locales/en/inventory.json
packages/common/src/schema.graphql
packages/common/src/types/schema.ts
packages/common/src/ui/components/inputs/DatePickers/DatePickerInput/DatePickerInput.tsx
packages/inventory/src/Stocktake/DetailView/Footer.tsx
packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
packages/inventory/src/Stocktake/DetailView/reducer.ts
packages/inventory/src/Stocktake/ListView/ListView.tsx
packages/inventory/src/types.ts
packages/inventory/src/utils.ts
packages/mock-server/src/data/data.ts
packages/mock-server/src/data/database.ts

Fixes #584 
- Just using suggested/finalised which is what I think msupply is using. I prefer new/finalised, so I thought if I used suggested/finalised then there would be more chance to lock in draft
- Added translations for the detail view and list view
- Made the next status button work

Add status translations and handling of save & next status button

---

packages/common/src/intl/locales/en/common.json
packages/common/src/intl/locales/en/inventory.json
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/common/src/utils/arrays/utils.ts
packages/inventory/src/Stocktake/DetailView/DetailView.tsx
packages/inventory/src/Stocktake/DetailView/reducer.ts
packages/inventory/src/Stocktake/ListView/ListView.tsx
packages/inventory/src/types.ts
packages/mock-server/src/data/data.ts

Fixes #585 
- At least partly :)
- I am not sure that these columns are right. You could add a bunch of things pack sizes, prices etc. but I though I would just do this for now and get feedback - the pieces are in place to lock in/add columns
- The sorting isn't working well. I started adding it and realised that I would need a new sorting function that needs to account for the `[multiple]` values but wanted to check in to see what would be best for that. Determining the aggregated value of the column (for say, counted number of packs) and sorting by that value (which doesn't work for say, batch) or just sorting all the `[multiple]` as either the 'first' or 'last' values in a sort 🤔

#585 Add item columns and summary items to stocktake detail view

---

packages/common/src/intl/locales/en/common.json
packages/common/src/intl/locales/en/inventory.json
packages/inventory/src/Stocktake/DetailView/DetailView.tsx
packages/inventory/src/Stocktake/DetailView/api.ts
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/index.ts
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
packages/inventory/src/Stocktake/DetailView/reducer.ts
packages/inventory/src/types.ts
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.ts

Fixes #587 
- Bit more substance to this one!
- This is adding a pretty basic stocktake edit modal similar to inbounds
TODO: Creating stocktake lines from existing stock lines. 
- I am thinking either having some sort of list which shows existing stock lines (maybe on the left or right of the modal..?) where you can check the stock lines and this adds a stocktake line to the item OR just creating the stock lines and if they're not counted then they get pruned (mobile style) OR having a column "Count this line" (more explicit but doesn't make sense for newly added lines) OR a combo box with tags
🤷  Not sure. Probably need to play around with some options

#587 stocktake edit item 1

---

packages/common/src/intl/locales/en/distribution.json
packages/common/src/operations.graphql
packages/common/src/schema.graphql
packages/common/src/types/schema.ts
packages/mock-server/src/data/data.ts
packages/requisitions/src/CustomerRequisition/DetailView/SidePanel.tsx
packages/requisitions/src/CustomerRequisition/DetailView/Toolbar.tsx
packages/requisitions/src/CustomerRequisition/DetailView/api.ts
packages/requisitions/src/CustomerRequisition/DetailView/reducer.ts
packages/requisitions/src/SupplierRequisition/DetailView/Toolbar.tsx
packages/requisitions/src/SupplierRequisition/DetailView/api.ts
packages/requisitions/src/SupplierRequisition/DetailView/reducer.ts
packages/requisitions/src/types.ts
packages/requisitions/src/utils.ts

Fixes #589
- Adds requisition + order date inputs to customer requisition
- Adds requisition date input to supplier requisition
I'm not sure where to put these was just trying to tick things off the list. Maybe should have waited for the meeting with dicky. I tried the side panel but thought that at least for customer requisitons that these dates were in a 'primary' position in mSupply so maybe they should go here - then wanted the consistency for supplier requisitions... even though i'm sure programs will throw everything into an inconsistent state

#589 requisition order and requisition dates

---

codegen.yml
packages/common/src/additions.schema.graphql
packages/common/src/operations.graphql
packages/common/src/schema.graphql
packages/common/src/types/schema.ts
packages/invoices/src/InboundShipment/DetailView/api.ts
packages/invoices/src/types.ts
packages/mock-server/package.json
packages/mock-server/src/api/resolvers/invoiceLine.ts
packages/mock-server/src/data/types.ts
packages/mock-server/src/index.ts
yarn.lock

Fixes #556 
- Took me a bit longer to get working than I had hoped..
- Ok this is generating types from the demo server. Good idea? Maybe.
- It's also taking the type defs from the server and merging with the additions when starting our apollo server
- Means we might have some annoyances when types are changed and added, but I suppose best we deal with that asap..
- It's pretty outrageous the amount of changes I needed to hack in just because of `item` being added to `InvoiceLineNode`. Was quite infuriating, actually! The way we're parsing the response using the generated types means that you need to query for all the required fields otherwise typescript barfs. Ugh! For now I've just added the overfetching. I *think* a solution might be to use fragments to generate smaller types, but I've …

#556 update gql schema 2

---

jest-setup.ts
packages/common/src/hooks/useListData/useListData.test.tsx
packages/invoices/src/OutboundShipment/ListView/ListView.test.tsx

Fixes #554 
Spent a while exploring various options and landed here. It was getting very involved trying to encapsulate and isolate the mock data generation.. and even then the `beforeAll` in `jest-setup.ts`wasn't keeping global state across the test suite, only for each test file. so I went back to the original problem, which is that the server was being instantiated for every test file and then the data generated for every test within every file. Simple solution was to lift that out and only setup the server for tests that use it (3 of them). Tests now run faster ( originally running ~80s now around 60s for the suite )

limit server setup in tests

---

packages/common/src/intl/locales/en/distribution.json
packages/common/src/intl/locales/en/inventory.json
packages/common/src/intl/locales/en/replenishment.json
packages/common/src/intl/locales/index.ts
packages/inventory/src/Stocktake/ListView/Toolbar.tsx
packages/inventory/src/utils.ts
packages/invoices/src/InboundShipment/ListView/Toolbar.tsx
packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
packages/invoices/src/utils.ts
packages/requisitions/src/CustomerRequisition/ListView/Toolbar.tsx
packages/requisitions/src/SupplierRequisition/ListView/Toolbar.tsx
packages/requisitions/src/types.ts
packages/requisitions/src/utils.ts

Fixes #450 
- I went with just stopping the mutation if there are selected rows that can't be deleted. Maybe it's not the best, but should do for now?
- The problem being that if you disable the button if these rows are selected, there's no feedback as to why it's disabled. If you only delete the rows which can be deleted, what feedback are you to give? "Deleted X rows, couldn't delete Y rows as you can only delete rows with a status of Z"? Seemed confusing to me?

#450 can delete finalised invoices

---

packages/common/src/hooks/index.ts
packages/common/src/hooks/useBufferState/index.tsx
packages/common/src/hooks/useBufferState/useBufferState.stories.tsx
packages/common/src/hooks/useBufferState/useBufferState.ts
packages/common/src/ui/components/inputs/TextArea/BufferedTextArea.tsx
packages/common/src/ui/components/inputs/TextArea/TextArea.tsx
packages/common/src/ui/components/inputs/TextArea/index.ts
packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
packages/common/src/ui/components/inputs/TextInput/BufferedTextInput.tsx
packages/common/src/ui/components/inputs/TextInput/index.ts
packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/SidePanel.tsx
packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
packages/invoices/src/InboundShipment/DetailView/api.ts
packages/mock-server/src/worker/handlers/invoice/index.ts
packages/system/src/Name/Components/NameSearchInput/NameSearchInput.tsx

Fixes #645 
- Went a bit further and was investigating some different ways to structure everything. Haven't got very far with that, but have added a hook `useInboundFields`. The idea being to get away from drilling the invoice down to every nook and cranny and instead, essentially use a selector hook closer to where data is used. This makes for a pretty clean and easy way to use the 'document'. I think the API is nice being able to destructure the values you ask for, though it could be going too far.
- I've added a 'buffer' state hook and debounced the api call. This means that inputs correctly 'update' their state, but the mutation is debounced. The problems I was trying to solve with this was that we could potentially have 'updates' come from the server (i.e. someone else editing the …

#645 debounced mutations

---

packages/common/src/intl/locales/en/replenishment.json
packages/common/src/operations.graphql
packages/common/src/types/schema.ts
packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
packages/invoices/src/InboundShipment/DetailView/api.ts
packages/mock-server/src/worker/handlers/invoice/index.ts

Fixes #445 
- Still need to add grouping here so I suppose this might change slightly, still as we will need to know if currently grouped, then the IDs are for summary items and so need to find the real invoice lines, otherwise they're for normal lines and we can just use the IDs.

#445 delete inbound lines

---

packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.test.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
packages/invoices/src/InboundShipment/DetailView/Footer.tsx
packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx

Fixes #677 
- Early return caused the number of hooks rendering to vary. doh, no idea how I did this!
- Then I thought to check tests and figured I'd do a quick fix for the breadcrumbs
- Then I noticed that the stocktake page was also having an error .. so I offroaded that also.
- Then I noticed the inbound shipment footer wasn't showing when it wasn't on hold... so I offroaded that also.

#677 inbound detail view crash

---

packages/common/src/styles/theme.ts
packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx
packages/common/src/ui/layout/tables/DataTable.tsx
packages/host/src/Host.tsx
packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx
packages/invoices/src/InboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx

Fixes #689 
- Ended up being a few different style updates
- Turned out the columns just weren't flexing because of the Grid added around the DataTable in the `GeneralTab`.. I think
- Then I made the scroll bar on the right 'auto' .. which when it wasn't showing when there were just a few items made the header row overlap the side panel .. so changed some zIndicies..

Add style updates

---

packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/Footer.tsx
packages/invoices/src/InboundShipment/DetailView/api.ts

Fixes #692 
- Turns out the problem was actually because the mutation was being debounced.. which gets into a bit more of a tricky problem: The mutation is debounced, so the optimistic update doesn't trigger. You could maybe do some other tricky dicky things like debounce the actual query rather than the 'update' function, which might be better? But I think you might get into more complicated situations where the cache has been updated, then a timer for a debounce query starts, and then something else updates the cache but doesn't update and doesn't cancel the query being sent and then other overrides happen.. or something? I'm not sure if it's really a problem, but I thought this would work for now.. though, also need to use that buffer state for the status button.. lucky they're right …

#692 inbound optimistic onhold

---

packages/common/src/operations.graphql
packages/common/src/types/schema.ts
packages/invoices/src/InboundShipment/ListView/ListView.tsx
packages/mock-server/src/api/resolvers/index.ts
packages/mock-server/src/api/resolvers/invoiceLine.ts
packages/mock-server/src/api/resolvers/location.ts
packages/mock-server/src/api/resolvers/stockLine.ts
packages/mock-server/src/data/data.ts
packages/mock-server/src/data/database.ts
packages/mock-server/src/data/types.ts
packages/mock-server/src/index.ts
packages/mock-server/src/schema/Location.ts
packages/mock-server/src/schema/index.ts
packages/mock-server/src/worker/handlers/index.ts
packages/mock-server/src/worker/handlers/location/index.ts
packages/system/src/Location/hooks/index.ts
packages/system/src/Location/hooks/useLocations.ts
packages/system/src/Location/index.ts
packages/system/src/index.ts

Fixes #510 
- I want to start correcting/completing the inbound cells in the edit modal, so wanted locations.
- Just the first query to get it on the board with all the boilerplate.. the hook I used in just the list view of the inbound shipment page and it's returning from the mock server and against the demo server

Add simple locations hook

---

packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditPanel.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx

Doesn't fix #703 🙃 
Some misc. fixes and setup for the real PR....! Also just getting my feet wet again after taking basically a year off!
- Fixed a bug which was making now batches show up for an edit
- Moved the 'static' columns into their own 'panel' component similar to how the stocktake modal is done - but I simplified it further by just using a second `DataTable`
- Fixed some big re-rendering issues where the currency input was always triggering 2 re-renders when first rendered. The table always still rerenders when switched to (i.e. the pricing table) but is only doing it once now 🎉

#703 locations to inbound

---

packages/common/src/hooks/useDialog/useDialog.tsx
packages/common/src/ui/components/buttons/FlatButton.tsx
packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
packages/common/src/ui/components/inputs/Switch/Switch.tsx
packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx
packages/common/src/ui/forms/Modal/ModalLabel.tsx
packages/host/src/components/AppBar/AppBar.tsx
packages/host/src/components/Footer/Footer.tsx
packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx

Fixes #465 
Found more items, and I expect that there are others I've missed. This is enough for now though!
Dashboard
Buttons
General Tab
Footer
Detail Panel

update RTL styles

---

packages/common/src/hooks/useDetailPanel.tsx
packages/common/src/localStorage/keys.ts
packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx

Fixes #694 
scratches an itch.. which, it turns out, shouldn't have been a problem 🙄 
The screen size detection was incorrect for the side panel, and on my little laptop screen it shouldn't have been showing anyway. Oh well, have persisted the state regardless.
Found that the panel should only show automatically at large screen sizes:

persist side panel state

---

packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx

Fixes #736 
- Filters out the items that have already been counted from being selected again.

Add filtering of items

---

packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/inventory/src/Stocktake/DetailView/ContentArea.tsx
packages/inventory/src/Stocktake/DetailView/columns.ts
packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx

Fixes #730 
- Added the expiry date formatter
- Changed some styles to improve the inbound shipment table and also ensure the expando is flexed (do we want this..? Seemed weird when the expand didn't fill the whole width, especially when the screen size was smaller and you were scrolling)

Add StocktakeDetailView row expansion

---

packages/common/src/intl/IntlProvider.tsx
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx
packages/invoices/src/OutboundShipment/DetailView/tabs/GeneralTab.tsx

Fixes #709
Had an issue with using `Collapse`, since it uses nested `div`s to get the animation effect.
So I've changed to use a `Fade` which affects the behaviour on first render of the table, I think it's kinda nice, so have left it. Can instead use props to only implement the fade when grouped if you prefer.
Couple of minor offroads - one was the table header change: the background was made white rather than transparent, which resulted in this:
I've put a border around the mini table to soften the impact of the square top of the first table row:
not sold on the big rounded corners.. but hopeful ok? 🤷

#709 dom violation

---

packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsForm.tsx
packages/invoices/src/OutboundShipment/DetailView/modals/ItemDetailsModal.tsx

Fixes #752 
couple of daft bugs 🐛  🙄 
As in the issue: changing the quantity would reset any changes to the selected pack size. The hook was happily resetting on every change. stopping that meant that the value was retained when editing a different line, which is a different problem. I've worked around by resetting the packSizeController state when you change the modal.

default pack size

---

packages/common/package.json
packages/common/src/intl/locales/en/app.json
packages/host/src/CommandK.tsx
packages/host/src/Host.tsx
yarn.lock

Fixes #761 
- Updated kbar ( for no good reason really, there was an error, but it was due to our config )
- Changed the styles of a few parts
- Search bar is now less orange ( opacity reduced to 0.2 so that the text is visible ), added a border
- Opacity of background + background colour
- Added z-index, though only required when shown over the data table due to the newly added zIndex of the header
- Some padding around list results
- border radius on results
- Modified the action list, added a bunch of routes, removed ones that were not working ( new outbound and navigation back )
- lifted kbar out to a sep file
- changed routes to use route builder
- added translation support for items

make kbar pretty again

---

packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx
packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
packages/system/src/Name/Components/NameSearchInput/NameSearchInput.tsx

Fixes #679 
Added the option to expand the popper width as needed, when doing so have set the `minWidth` because I think it looks silly when the popper is not as wide as the input.
Added `boxShadow` to all Autocompletes as I think it looks nice.
Updated the name search input to use auto width; added a story to demonstrate the option.

tidy autocomplete styles

---

packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditPanel.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx

Fixes #734 
Removed the batch and expiry table and moved those columns into each of the other tables.
To support that -
- added a `maxWidth` prop
- added a `backgroundColor` prop : went with the specific use case, rather than a more helpful implementation of `style`. when we need that, we can add it in and remove the background colour
- adjusted the row padding: as the fixed height, combined with the really big padding meant that the background overlayed and looked too dark in between the rows. As it is, I've used slightly more padding than necessary to hide the expando row

remove batch & expiry table

---

packages/common/package.json
packages/common/src/api/OmSupplyApiContext.tsx
packages/common/src/hooks/usePagination/usePagination.ts
packages/common/src/hooks/useSortBy/useSortBy.ts
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/context/TableContext.ts
packages/common/src/utils/formatters.ts
packages/invoices/src/InboundShipment/DetailView/api.ts
packages/invoices/src/InboundShipment/DetailView/columns.ts
packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
packages/invoices/src/OutboundShipment/DetailView/api.ts
packages/invoices/src/OutboundShipment/DetailView/columns.ts
packages/invoices/src/OutboundShipment/api/api.ts
packages/invoices/src/types.ts
packages/mock-server/src/data/database.ts
yarn.lock

Fixes #733 
- The main thing I concentrated on here was the heavy rendering. There were previously quite a few renders 200ms+. Now the heaviest is 40ms. It feels snappy!
- Memo'd the `DataTable` with a hacky solution (because of generic types)
- Removed the `useSearchParams` usage. Not sure if the right thing to do 😢 
- Made the data row expansions only render when expanded
- more memoising in various key places
- main one: removed the parsing of expiry dates into real dates in the query fn. This was making react-query think the data had changed, so was causing reference instability and re-rendering all of the things

#733 modal perf issues

---

packages/common/src/hooks/useHostContext.ts
packages/common/src/localStorage/keys.ts
packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/host/src/Site.tsx
packages/host/src/components/AppDrawer/AppDrawer.tsx
packages/host/src/components/Footer/Footer.tsx
packages/host/src/components/Login/Login.tsx
packages/host/src/components/Login/hooks.ts
packages/host/src/components/Navigation/RequireAuthentication.tsx
packages/mock-server/src/api/resolvers/index.ts
packages/mock-server/src/api/resolvers/store.ts
packages/mock-server/src/data/data.ts
packages/mock-server/src/data/database.ts
packages/mock-server/src/data/types.ts
packages/mock-server/src/worker/handlers/authentication/index.ts
packages/mock-server/src/worker/handlers/index.ts
packages/mock-server/src/worker/handlers/store/index.ts

Fixes #773 
Adds the mock queries - not certain it is helpful, but it's fun to do.
The login allows a password starting with `pass` and rejects otherwise
Added the requirement for authentication too, only enforced in production though.. don't want to be annoying the devs.
Will probably need to timeout the session, and will need to add the token and store id to queries.. can do that later I think.

#773 auth storage

---

packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.tsx
packages/invoices/src/OutboundShipment/DetailView/Footer.tsx
packages/invoices/src/OutboundShipment/api/hooks.ts
packages/mock-server/src/api/mutations/invoice.ts
packages/mock-server/src/data/database.ts

Fixes #777 
- This enables using the mock server to change statuses
- Also disables on the correct status
- Off road fix for the status text on the popover

Add enabling status changes for outbound shipments

---

packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/Footer.tsx
packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
packages/invoices/src/InboundShipment/DetailView/api.ts
packages/invoices/src/utils.ts
packages/mock-server/src/api/mutations/invoice.ts
packages/mock-server/src/data/database.ts

Fixes #686 
- This adds some changes to inbound shipment statuses to hopefully get them working somewhat close to the desired behaviour
- You'll notice that when creating an ad hoc inbound shipment the status is `new`. Then, when changing the status, we skipped to delivered. This is because 'picked' and 'shipped' should be set when the corresponding customer invoice status is set. Maybe it would be better if the original status was `shipped`. However, you can't change any statuses @ `shipped`, nor change the status to `shipped`, so if we want to change this behaviour we will need API changes.
- Also you'll notice the statuses are grey'd out. This is because the component is actually checking the dates corresponding to the status to determine completeness. Unsure if this is good or not, …

#686 Inbound shipment statuses

---

packages/invoices/src/OutboundShipment/DetailView/modals/OutboundLineEditForm.tsx

Just a minor mistake slipped through causing a crash when opening the outbound line edit

Add defensive code protecting against invalid value access

---

packages/common/src/intl/locales/en/common.json
packages/common/src/ui/components/buttons/ButtonShowcase.stories.tsx
packages/common/src/ui/components/buttons/SplitButton.stories.tsx
packages/common/src/ui/components/buttons/SplitButton.tsx
packages/common/src/ui/components/buttons/index.ts
packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx

Fixes #813 
- Adds a split button component
- Not sure about the design of it, but the functionality is there! Specifically, the shrinking to just an icon. It has a tooltip, but might still be confusing?
- Idea is to have a list of different statuses to choose and 'skip'

Add split button component

---

packages/common/src/additions.schema.graphql
packages/common/src/operations.graphql
packages/common/src/types/schema.ts

Fixes #540 
removed the duplicate - though this is fairly pointless. the requisitions is about to change anyway.
For that reason, haven't updated the status, sort or filter. that'll be done soon enough with the API integration.

minor tidy

---

packages/common/src/intl/locales/en/common.json
packages/common/src/intl/locales/en/distribution.json
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.stories.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.stories.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
packages/common/src/ui/components/modals/ConfirmationModal/index.ts
packages/common/src/utils/testing.tsx
packages/host/src/Host.tsx
packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx

Fixes #792 
- Adds a provider with `ConfirmationModal` and a hook `useConfirmationModal`
- Adds use of the above hook in the status change area of the outbound shipment detail view
- Unsure of the copy but .. 🤷

#792 status confirmation

---

packages/requisitions/src/RequisitionService.tsx
packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx
packages/requisitions/src/SupplierRequisition/api/api.ts
packages/requisitions/src/SupplierRequisition/api/hooks.ts
packages/requisitions/src/SupplierRequisition/api/operations.generated.ts
packages/requisitions/src/SupplierRequisition/api/operations.graphql

#831 
- Using `storeID` from host context in the request requisition queries
- Using `requisitionNumber` for querying for the detail view

#831 Use storeID and requisition number for request requisition queries

---

packages/host/src/CommandK.tsx
packages/requisitions/src/RequisitionService.tsx
packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
packages/requisitions/src/ResponseRequisition/api/api.ts
packages/requisitions/src/ResponseRequisition/api/hooks.ts

Fixes #854 
- Adds use of `requisitionNumber` for navigating to response reqs (I had to use a local copy of remote-server to test this, rather than the demo server)
- Off-road added internal orders to commandK - though I didn't add a shortcut as all the letters are taken!!

#854 use requisition numbers for responses

---

packages/common/src/hooks/useDrawer.ts
packages/common/src/styles/RTLProvider.tsx
packages/common/src/styles/ThemeProvider.tsx
packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.test.tsx
packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
packages/host/src/components/AppDrawer/AppDrawer.tsx
packages/host/src/components/Navigation/CatalogueNav.tsx
packages/host/src/components/Navigation/DistributionNav.tsx
packages/host/src/components/Navigation/InventoryNav.tsx
packages/host/src/components/Navigation/ReplenishmentNav.tsx
packages/host/src/components/Navigation/useNestedNav.ts
packages/host/src/routers/CatalogueRouter.tsx
packages/host/src/routers/InventoryRouter.tsx

Fixes #815 
Removes the dodgy hover / expand function on the drawer. Wasn't working terribly well. 
Took the hover off the menu elements and moved to the drawer itself, no need to be on elements with the move to an onClick for the parent nav items.
Also shifted master lists to Catalogue rather than Inventory as suggested by Richard - made sense to me.

Remove drawer hover expand

---

packages/common/src/styles/theme.ts
packages/common/src/styles/useAppTheme.ts

Fixes #886 ( maybe!! )
Setting the direction to `ltr` and reloading in Arabic makes the autocomplete behave incorrectly in a different way ( the caret is incorrect and moves when the select is expanded ).. so I figure this is similar.
The actual problem was when using an ltr language, the mui classes `rtl-` were applied to all the things. so there was something amiss with the mui theme. Hoping this helps 🤞

Set theme direction

---

packages/common/src/intl/locales/en/common.json
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/common/src/utils/NumUtils.test.ts
packages/common/src/utils/NumUtils.ts
packages/common/src/utils/index.ts
packages/common/src/utils/quantities.test.ts
packages/common/src/utils/quantities.ts
packages/requisitions/src/RequestRequisition/DetailView/columns.ts
packages/requisitions/src/ResponseRequisition/DetailView/columns.ts

Fixes #895
- Have updated the columns for request and the item columns for responses. I'm not sure about the columns for responses I don't think the spreadsheet is accurate https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=320810900&range=A233:S233 and haven't seen any mock ups 🤔

#895 internal order columns

---

packages/common/src/hooks/useQueryParams/useQueryParams.ts
packages/common/src/hooks/useSortBy/useSortBy.ts
packages/common/src/types/index.ts
packages/common/src/types/utility.ts
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx
packages/common/src/ui/layout/tables/columns/ExpiryDateInput/ExpiryDateInput.tsx
packages/common/src/ui/layout/tables/columns/LineLabel/LineLabel.tsx
packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx
packages/common/src/ui/layout/tables/columns/NotePopoverColumn/NotePopoverColumn.tsx
packages/common/src/ui/layout/tables/columns/RowExpand/RowExpand.tsx
packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx
packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/common/src/ui/layout/tables/components/index.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.test.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/common/src/ui/layout/tables/types.ts
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.test.ts
packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
packages/invoices/src/InboundShipment/DetailView/GeneralTab.tsx
packages/system/src/Location/Components/LocationInputColumn.tsx

Fixes #929 
- We can go with either `DomainObject` or `RecordWithId` whichever you prefer, but I thought it would be better to stick to one instead of having `DomainObject = RecordWithId` and using `DomainObject` everywhere 🤷

Add find and replace for DomainObject -> RecordWithId

---

packages/common/src/authentication/AuthContext.tsx
packages/common/src/intl/locales/en/app.json
packages/host/src/components/Footer/Footer.tsx
packages/host/src/components/Footer/StoreSelector.tsx

Fixes #958
While not strictly speaking a requirement.. it is handy. 
Just popped in a sneaky `onClick` on the store, pop up a list of stores, click and change. No one needs to know..

add store selector

---

packages/common/src/intl/locales/en/distribution.json
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.stories.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.stories.tsx
packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx
packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons.tsx
packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
packages/requisitions/src/RequestRequisition/api/api.ts
packages/requisitions/src/RequestRequisition/api/hooks.ts
packages/requisitions/src/RequestRequisition/api/operations.generated.ts
packages/requisitions/src/RequestRequisition/api/operations.graphql
packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons.tsx
packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
packages/system/src/MasterList/api/index.ts
packages/system/src/MasterList/index.ts

Fixes #581 
- Minor change to `useConfirmationModal` which I hope is a good change, but made diffs in a fair amount of files
Essentially the issue being:
```
const { mutate } = useMutation(api.addFromMasterList)
const addFromMasterList = async (masterList) => {
await  mutate(masterList)
}
const getConfirmation = useConfirmation({text: "are you sure", message: "yes I'm sure!", onConfirm: () => { ... } })
return <MasterListSearchModalList onChange={masterList => { 
toggleOff(); 
// ---- Need to open the confirm here and also pass the master list into the onConfirm callback ----
// ---- would need to set some state with the master list and then trigger the getConfirmation   ----
// ----  with a useEffect.. Then, remember to clear the state! 
// ---- so, instead:
getConfirmation({ onChange: …
```

#581 Add from master list - A kind stranger made this PR and got an UNFORGETTABLE SURPRISE -- [7]

---

packages/common/src/hooks/useDialog/useDialog.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
packages/system/src/Item/Components/ItemSearchInput/ItemSearchInput.tsx

Fixes #989 
- Just wanted to add a little auto focus... and then..
- I added `openOnFocus` to the autocomplete which was kind of nice, but I was having a little bit of an issue where the list box of the auto complete was not aligning well after a transition animation. Weird. So I left that out and just went with the autoFocus (If you want to see, add `openOnFocus={true}` to the autocomplete..
- I realised the next behaviour was a little inconsistent in all the modals. Some were disabling while the modal was in Create mode. But I wanted it enabled! Especially with the auto focus it makes it really easy to add items with the next button. Though, it does make things a little inconsistent still - the next behaviour during 'update' mode - disabling the next button? Closing the modal when there …

#989 auto focusing item input

---

packages/common/src/api/GqlContext.tsx
packages/common/src/api/OmSupplyApiContext.tsx
packages/common/src/api/index.ts
packages/common/src/authentication/AuthContext.tsx
packages/common/src/authentication/api/hooks/useAuthApi.ts
packages/common/src/utils/testing.tsx
packages/dashboard/src/api/hooks.ts
packages/host/src/Host.tsx
packages/inventory/src/Stocktake/api/hooks.ts
packages/invoices/src/InboundShipment/api/hooks.ts
packages/invoices/src/OutboundShipment/api/hooks.ts
packages/requisitions/src/RequestRequisition/api/hooks.ts
packages/requisitions/src/ResponseRequisition/api/hooks.ts
packages/system/src/Item/api/hooks/useItemApi/useItemApi.ts
packages/system/src/Location/api/hooks.ts
packages/system/src/MasterList/api/hooks.ts
packages/system/src/Name/api/hooks.ts
packages/system/src/Stock/api/hooks.ts
packages/system/src/Store/api/hooks.ts

Fixes #976 
- Renamed `OmSupplyApi` -> `GraphQLClient`
Realised there were other options 😭  Think I prefer `GqlClient` or `Gql` 😁 
`useGqlClient` / `useGql` / `GqlProvider` / `GqlClientProvider`
What about you?

Add rename OmSupplyApi -> GraphQLClient

---

packages/common/src/hooks/useFilterBy/useFilterBy.tsx
packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx

Fix #1052 
Explicitly clears the filter field when the filter string is empty.

#1052 Clear filter when filter input empty

---

packages/common/src/api/hooks/useQuerySelector/README.md
packages/common/src/api/hooks/useQuerySelector/useQuerySelector.ts
packages/host/src/Host.tsx
packages/inventory/src/Stocktake/api/hooks.ts
packages/invoices/src/InboundShipment/api/hooks.ts
packages/invoices/src/OutboundShipment/api/hooks.ts
packages/requisitions/src/RequestRequisition/api/hooks.ts
packages/requisitions/src/ResponseRequisition/api/hooks.ts
packages/system/src/MasterList/api/hooks.ts

Fixes #1001 
- Adds a default option to the react query client for `notifyOnChangeProps`
- Also adds some props to the`useDetailDocument` type hooks

Add adjustments to react-query props

---

packages/system/src/MasterList/api/api.ts

Fixes #1014 
- Pretty simple update. If adding an outbound add from master list mutation, would want to use a filter of both `existsForName` (with the customer nameID) and `existsForStore`

#1014 filter master lists

---

packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts

Fixes #1051 
Don't show a tooltip if there is nothing to say; and forward the ref to the non-sortable header if there is a description.

Tooltips on headers

---

packages/common/src/ui/components/buttons/IconButton/IconButton.tsx
packages/host/src/components/AppDrawer/AppDrawer.tsx

Fix #1074 
Was a tiny fix -- see what you think. (Seems useful to have the full `sx` props passed down from the `IconButton` anyway.)

#1074 mSupply man hover background

---

packages/common/src/api/GqlContext.tsx
packages/common/src/authentication/AuthContext.tsx
packages/common/src/intl/locales/en/app.json
packages/common/src/localStorage/keys.ts
packages/host/src/Host.tsx
packages/host/src/components/AuthenticationAlert.tsx

Fixes #1096, #1101 
Yes, that's right! two-for-one time! 😁 
These two are somewhat interrelated, so I've combined them in one PR. uh, sorry.
Few things
- Checking the response of every gql request and if it has the 'unauthenticated' error, then pop that into local storage. Ideally I would have updated the `AuthContext` directly but there is a problem of dependency. The AuthContext uses a gql request so has to sit under the gql provider. Also slightly annoying using the AuthContext without referencing hooks directly.. so it was good to sidestep that
- The `LoggedOutAlert` is now more generic and so has been renamed
- The `AuthContext` is running an interval, checking the cookie and if it has expired, or no token - sets an `AuthError`
- The `AuthenticationAlert` is using the `AuthError` …

authentication check

---

packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/common/src/utils/dates/DateUtils.ts

Fix #1114 
Turns out the 1/1/1970 date wasn't being saved, it was just a small problem with the Date formatter not handling `null` values correctly.
Slightly tangential: noticed that the sort headers weren't working on this table. Turns out that API isn't accepting those columns as sort keys -- have made an issue for back-end: https://github.com/openmsupply/remote-server/issues/981

#1114 Stockdate date fix

---

packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
packages/common/src/ui/layout/tables/DataTable.tsx
packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx
packages/common/src/ui/layout/tables/columns/types.ts
packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx
packages/common/src/ui/layout/tables/components/Header/Header.tsx
packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
packages/inventory/src/Stocktake/ListView/ListView.tsx
packages/invoices/src/InboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/DetailView/columns.ts
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
packages/system/src/Location/Components/LocationSearchInput.tsx

Fix #1097 
General gist is:
- remove defaults for column `minWidth` and `width` (Table will auto-width unless custom width style is specified)
- remove "flex" layouts on the table elements (Header, Body, Row) as it was making a mess of the column widths per row once defaults were removed
Have add custom widths to some columns, but they're pretty arbitrary just based on me eye-balling it with the existing data -- will probably want to evolve them over time.
Have checked all the tables, including ones with grouped lines, and they seem to be behaving themselves.

#1097 Table column widths

---

packages/common/src/hooks/index.ts
packages/common/src/hooks/useGetPageTitle/index.ts
packages/common/src/hooks/useGetPageTitle/useGetPageTitle.tsx
packages/common/src/hooks/useHostContext/useHostContext.ts
packages/common/src/intl/locales/en/app.json
packages/common/src/intl/locales/en/common.json
packages/host/src/Site.tsx
packages/host/src/components/Login/Login.tsx

Fix #1120 (no for real this time ;) )
Was easier to just create a new branch. This contains page title implementation as discussed on #1122. 
Put `pageTitle` and `setPageTitle` into `useHostContext`. However, still had to make a new hook to map routes to titles, as I couldn't access the `useTranslation` hook from within the zustand `create` function.

#1120 (2) Page title

---

packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx

Fix #1128 
This crept in when I was updating the row hover styles the other day. Didn't realise I the hover style also over-rode the effect of the `hover` prop in `<TableRow>`.
Have removed the `hover` prop completely and made the hover style conditional.

#1128 Row hover fix

---

packages/common/src/ui/components/modals/AlertModal/AlertModal.tsx
packages/common/src/ui/components/modals/AlertModal/AlertModalContext.tsx
packages/common/src/ui/components/modals/AlertModal/AlertModalProvider.tsx
packages/host/src/components/AuthenticationAlert.tsx

Fixes #1134 
Well, that turned out to be a good one to sort out. The `AlertModal` is used in multiple places, at different levels in the document hierarchy. Turns out, the provider wasn't adding anything and multiple instances of the modal were being created 🙄 
A simple test.. In the `Internal Orders` detail page add
```
const [error, setError] = useLocalStorage('/auth/error');
```
and 
```
React.useEffect(() => {
setTimeout(() => {
if (!error) setError(AuthError.Unauthenticated);
}, 1000);
}, []);
```
and then change the requisition number in the URL to an invalid one for your store.
you should get two modals, overlayed, with the 'requisition not found' appearing on top.
This PR fixes that.

Prevent duplicate alert modals

---

packages/common/src/hooks/useDirtyCheck/useDirtyCheck.ts
packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx

Fix #1100
Just used the existing `isDirty` state to conditionally run the mutation for saving. Plus set `isDirty` back to `false` in a couple of places where it needed to be.
Currently just affects the Inbound/Output shipment line edit modals. Any other places we should have this? (These are the only places where `useDirtyCheck` hook is being used)

#1100 Don't mutate if no changes

---

packages/common/src/hooks/useDrawer/useDrawer.ts
packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx

Fixes #1165 
Opens the drawer (if closed) on click, and if the drawer was opened this way, closes on clicking a menu item.
It does mean that you can open the drawer by clicking on a category menu item and then leave the drawer open by clicking on something in-page, like navigating to a detail page. Still.. this is better than it was.

Open on click nav link

---

packages/common/src/intl/locales/en/app.json
packages/system/src/Report/components/ReportSelector.tsx

Fixes #1159 
Renames the selection heading and prints without prompting if there is only one report.
To aid in testing, I've created a new 'invoices' report.. so outbound and inbound will still show the selection popover.

Tidy report usage

---

packages/common/src/intl/strings/IntlStrings.ts

fixes #884 
well, that was simpler than expected.
Simple test, from the issue itself. Just add
```
const [state, setState] = React.useState(0);
const t = useTranslation();
useEffect(() => {
console.log(`** RENDER ${state} **`);
setState(state + 1);
}, [t]);
```
to a page and watch the fun.

Stabilise translation hook

---

packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
packages/invoices/src/OutboundShipment/DetailView/columns.ts

Fixes #1205 
The currency and expiry date formatting is now in the column definitions and if called twice results in an empty string.

Remove duplicated formatting

---

packages/common/src/utils/regex/RegexUtils.tsx
packages/system/src/Stock/ListView/ListView.tsx

Fixes #1203 
There's a temporary filter in place to allow filtering by either item code or name - complete with a dodgy regex. Have escaped search chars

Escape stock filter

---

packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx
packages/common/src/ui/layout/tables/context/TableContext.ts
packages/common/src/ui/layout/tables/context/hooks/useExpanded.ts
packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
packages/inventory/src/Stocktake/DetailView/Toolbar.tsx

Fixes #776 
Well, that took longer than expected! 
The root of the issue was that we are rendering a `DataTable` to show the expando content.. and that wasn't instantiating a new table context. This meant that the expanded state was being reset - by playing with the rendering, the table row had to be rendered and with the reset table context, it wasn't expanded anymore! 🙄

Render expando only when expanded

---

packages/common/src/hooks/useFilterBy/useFilterBy.tsx
packages/common/src/hooks/useQueryParams/useQueryParams.ts
packages/common/src/ui/layout/tables/context/TableContext.tsx
packages/invoices/src/OutboundShipment/ListView/ListView.tsx
packages/invoices/src/OutboundShipment/api/hooks/document/useOutbounds.ts

Fixes #1204 
Am creating the PR at this stage.. there is more refactoring to do, but I want to reduce the number of files in the PR 😉 
This one is the essence of the change - the next steps are:
- replicate these changes across all usages of `useQueryParams`
- remove the hooks `useFilterBy` `useSortBy` & `usePagination`
- rework existing tests
The core of the problem is that the current hooks aren't sharing state.. so a list of items is retrieved by two separate calls, and each has different query params, though the code is expecting to see the same list of results.
I've lifted the queryParams state out, so it is created in the page context. Almost always, this is within the table context, so have created a query params context which is instantiated by the table context. For the cases …

Refactor userQueryParams for Outbounds

---

packages/common/src/intl/locales/en/inventory.json
packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
packages/inventory/src/Stocktake/DetailView/DetailView.tsx
packages/invoices/src/InboundShipment/DetailView/ContentArea/ContentArea.tsx
packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx

Fixes #1235 
Remove the link on the detail view when the record is disabled for the following:
- Inbound shipment
- Outbound shipment
- Internal order
Added bonus: noticed that the stocktake detail wasn't using the <NothingHere/> component, so have popped that in too

Remove add item when disabled

---

README.md
packages/common/src/api/GqlContext.tsx
packages/common/src/authentication/AuthContext.tsx
packages/common/src/localStorage/LocalStorage.ts
packages/common/src/localStorage/useLocalStorage.ts
packages/host/src/Host.tsx
packages/host/src/components/AuthenticationAlert.tsx
packages/host/src/components/Initialise/hooks.ts

Fixes #1237 
This is overboard, possibly? I've wandered off a little here, just to show this:
which was not being displayed any longer, since the permission denied error was being set after this error was ( the dashboard queries were triggering them), and therefore the permission denied modal was shown instead of this one. To get things working, I've had to add a request check function into GqlContext which allows the skipping of requests.
The _actual_ issue was not very complex. It came from the health supply hub, which is using a copy of `common` and having auth issues, because the line which resets auth state on login was removed. To make things clearer, I've lifted that out to a helper method ( thanks @jmbrunskill for the heads up on that one! )

Auth error state set & reset

---

packages/common/src/intl/context/IntlContext.tsx

Fixes #1241 
Oops. Update the language detection order, so that localStorage is before the new custom navigator detection 🙄

Language detection order

---

.gitignore
packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx

Fixes #1249, #1244
The problem is partly a user error. Clicking the add item in the NothingHere component gave the error, using the app bar button is fine. Just had to update the usage of `addItem` for outbounds

Outbound: add item
